droplet_actions.go, droplet_actions_test.go
This is an old branch I had laying around from when I was first looking at godo and Actions requiring parameters were broken, cleaned up and rebased on master. It add support for taking snapshots.
=> Add support for DropletActions.Snapshot.

droplets.go, droplets_test.go
This should fix #18 
The tl;dr of #18, is that the `Network.Netmask` field is a string, but depending on whether the interface is IPv4, or IPv6, the v2 API will return a different type for that field; (`string` for IPv4, `int` for IPv6). The reason for the splitting of the `Network` type into `NetworkV4` and `NetworkV6`, is so that everything unmarshals cleanly.
I have also added tests.
=> Fix inability to list droplets with IPv6 addresses

README.md
I think most people would figure it out, but it's better to have the example work right off the bat.
=> Added godo to DropletCreateImage in create example

droplets.go, droplets_test.go, godo_test.go
An issue with creating a droplet where the region does not support user data. Due to the string being empty and not sent as null it will cause the server to error out telling the user that the region does not support user data.
Described in more detail by an issue created by me. #37
=> Omit an empty value for user data to serialize properly.

droplets_test.go, images.go, images_test.go
The following were added:
* Images.ListDistribution() for GET /v2/images?type=distribution
* Images.ListApplication() for GET /v2/images?type=application
* Images.ListUser() for GET /v2/images?private=true
* Images.GetByID() for GET /v2/images/12345
* Images.GetBySlug() for GET /v2/images/ubuntu
* Images.Update() for PUT /v2/images/12345
* Images.Delete() for DELETE /v2/images/12345
Also the Image struct now has a "Type" and "MinDiskSize" fields.
=> Add missing APIs to Images service.

util/droplet_test.go
WaitForActive can be used to block until a droplet comes up. Adding
an example of its usage.
=> Add example for WaitForActive()

godo.go, godo_test.go
This makes it possible for consumers of the package to debug requests made to the DO APIs, usage:
```go
client.OnRequestCompleted(func(req *http.Request, resp *http.Response) {
// ... e.g. use httputil.DumpRequest / httputil.DumpResponse
})
```
=> Add optional API request completion callback to client.

droplets.go, droplets_test.go
Adds missing size_slug to the Droplet struct.
Fixes #21
=> Add size slug to droplet

README.md
As per https://code.google.com/p/goauth2/ goauth2 is deprecated. Updated the readme example accordingly to use the recommended new library.
cc @aybabtme @macb @bryanl @nickvanw @jphines
=> Update to oauth2 example.

godo.go, godo_test.go
When adding options to a path, don't drop existing keys. This will enable image pagination when there is a type key to work. The bug was trying to addOptions to an existing path with query values. Previously if a path `/path?type=alpha` was passed, key `page=2` would be appeneded, but `type=alpha` would be dropped.
=> Don't drop existing query keys

account.go, account_test.go, domains.go, domains_test.go, droplet_actions.go, droplets.go, droplets_test.go, godo_test.go, images.go, keys.go, links.go
This standardizes the client responses to return objects, not json document roots. 
* We're inconsistent about this. We already return the object from DropletActionsService, ImageActionsService, DomainsService.CreateRecord, KeysService
* Implementers don't care about the root object, they care about the object. Even when the user needs access to the Links, that's accessible via the `resp` variable returned, as is shown in the example in the readme.
cc @aybabtme @macb @bryanl @nickvanw @jphines
=> Standardize on returning objects, not the json roots.

droplet_actions.go
Removing unexported `doAction` from DropletActionsService interface because it makes DropletActionsService impossible to mock.
=> Remove unexported item from interface

droplets_test.go, images.go, images_test.go
Add standard `created_at` attribute exposed from [Images API](https://developers.digitalocean.com/documentation/v2/#images).
=> Add Created attribute to Image

action.go, domains.go, droplet_actions.go, droplets.go, errors.go, errors_test.go, image_actions.go, images.go, keys.go
Adds checks to determine if the request will actually be valid by prefiltering invalid defaults (less than 0, empty strings, nils). The goal of this change is eliminate unnecceary API calls.
=> Add checks for arguments

floating_ips_actions.go, floating_ips_actions_test.go
Adds the missing `List` action for Floating IP Actions. This GET endpoint is also missing from the API docs (I opened feedback [here](https://digitalocean.uservoice.com/forums/136585-digitalocean/suggestions/10798782-the-get-action-on-floating-ip-ip-actions-should)) .
This is also blocking hashicorp/terraform#3748 , so an expedient review would be appreciated! Test is included.
=> Add List action for Floating IP Actions

droplets.go
it was already available in the fetched JSON
=> make current kernel available in a Droplet

droplets.go, droplets_test.go
Introduces new functions for `github.com/digitalocean/droplet` to make fetching IP address easier.
* PublicIPv4
* PublicIPv6
* PrivateIPv4
=> Expose convenience methods to expose droplet IPs

droplets.go, droplets_test.go
ActionIDs for Droplets were removed a while go. This removes support the API client.
=> Remove ActionIDs from Droplets

godo.go, godo_test.go
Allow for easier and more explicit customization of Client at
initialization. Introducing a new constructor as to not upset the existing
exports.
Fixes: #84
=> create functional option based initializer for Client

godo_test.go
> Go 1.7 adds support for maps using keys with integer types: the
> encoding uses a quoted decimal representation as the JSON key.
in: https://tip.golang.org/doc/go1.7, under encoding/json
=> remove JSON invalid encoding test

godo.go, godo_test.go
I've added tests to make sure both `godo.New()` and `godo.NewClient()` initialize the different services.
Fixes #97
=> Make sure godo.New() init the different services

godo.go, godo_test.go
=> Changing the User Agent doesn't work as expected

droplets.go, droplets_test.go, godo.go, storage.go, storage_actions.go, storage_actions_test.go, storage_test.go
This adds support for block storage.
__note__: snapshots are still WIP/beta/unstable, and thus to _link_ against this code, you need to get out of your way and type-assert the Beta features.  I think that's a fair compromise, I'm open to alternatives or straight up just deleting the snapshot code.
=> storage: support for beta storage API

droplets.go
Moves `dropletCreateImage` receiver's `MarshalJSON` to be under the `struct` definition for easier visual groking.
- ~~Types, structs and funcs should be documented.~~ N/A, no code addition
=> organizes dropletCreateImage MarshalJSON declaration

droplets.go, droplets_test.go, godo_test.go
This allows `tags` to be sent in droplet create requests.
https://developers.digitalocean.com/documentation/changelog/api-v2/tagging-in-droplet-create/
@daveworth @hugocorbucci
=> Add Tags attribute to droplet create

droplets.go
Hey there! I'm @ UC Berkeley working on Quilt, a distributed application deployment engine, (https://github.com/NetSys/quilt/). I'm currently adding cloud provider support for DigitalOcean, which is how I found this bug.
The Droplet struct had the wrong JSON key for VolumeIDs, so volumes would not be reflected in a Droplet query.
=> Fix droplet JSON to support VolumeIDs

droplets.go, godo.go, snapshots.go, snapshots_test.go, storage.go, storage_test.go
https://developers.digitalocean.com/documentation/changelog/api-v2/add-volume-snapshots/
cc @andrewsomething @mikejholly @mjsteger
=> Add snapshots endpoints.

snapshots.go, snapshots_test.go
@phillbaker  My [little sample program](https://gist.github.com/andrewsomething/d43ccaf333531001612647405188d4ac) still fails when listing snapshots.
> Something bad happened: json: cannot unmarshal number 3.27 into Go value of type int64
SizeGigaBytes should be a float.
=> SizeGigaBytes is an floating-point number.

storage.go, storage_test.go
Follow up to https://github.com/digitalocean/godo/pull/108 based on feedback. removes `Beta` Interface.
cc @aybabtme
=> Remove betastorageservice, in production.

droplets.go, droplets_test.go, godo_test.go
This adds the `monitoring` boolean flag to `DropletCreateRequest` and `DropletMultiCreateRequest`.
DO NOT MERGE until API is updated!
=> Adds support for creating droplets with monitoring

droplet_actions.go, droplets.go, godo.go, links.go, regions.go, snapshots.go, storage_actions.go, storage_actions_test.go, strings.go, tags.go, tags_test.go, timestamp_test.go
Running linters on the package comes back with a number of stylistic errors relating to commenting, some cyclic complexity, opportunities for the use of an interface, and some shadowed/ineffectual/downright missing error checks. I fixed them so the Go report card looks clean(er). Tests run still,
=> make linters happy

godo_test.go
Added TestCustomBaseURL and TestCustomBaseURL_badURL to godo_test.go to help test the SetBaseURL function.
This will help validate Client.BaseURL field matches the defined url when setting in Client.New(nil, SetBaseURL("url").
Also added test to handle errors on url.Parse to ensure that we return err as expected.
Thanks. 
(fyi..  New to golang/opensource and learning so much from godo and doctl projects!!)
=> adding tests for godo.SetBaseURL()

storage.go, storage_test.go
This allows you to get a volume by name and region which corresponds to
calling:
```
/v2/volumes?name=$NAME&region=$REGION
```
=> Add GetVolumeByName to Storage

certificates.go, certificates_test.go, godo.go
This change set adds support for managing certificates with the DigitalOcean API @ https://developers.digitalocean.com/documentation/v2/#certificates
=> Add CertificatesService for managing certificates with the DigitalOcean API.

image_actions.go, image_actions_test.go
This Pull Requests implement Convert Image action. For example, convert image can be used to convert an backup to a snapshot.
Action is described in [Convert - Image Actions](https://developers.digitalocean.com/documentation/v2/#convert-an-image-to-a-snapshot) API docs.
It's a very similar to a Transfer action. It could be made into one function, but it would require a `Transfer` rename.
I'm not sure about project backward compatibility policy, so I decided to go with another function.
Because `ActionRequest` is fixed, and is always taking the same data - `type: convert`, I predefined it.
If it's the problem, I'll go ahead and make it same as the `Transfer` action.
This also comes with a test unit for action.
cc @mauricio @aybabtme
=> Implementing Image Convert action

storage_actions.go, storage_actions_test.go
The function returns "422 Attachment not found" all the time (tested
with doctl), and the doc* also says that droplet id should be
specified.
* https://developers.digitalocean.com/documentation/v2/#remove-a-block-storage-volume-from-a-droplet
=> Remove non-working Detach function

tags.go, tags_test.go
Per [our changelog](https://developers.digitalocean.com/documentation/changelog/api-v2/deprecating-update-tag/), tag rename will be deprecated on April 26, 2017.
cc @mauricio @hugocorbucci @magicgrl111
=> Deprecate tag rename (PUT /v2/tags/:name)

.travis.yml, account.go, action.go, certificates.go, context/context.go, context/context_go17.go, context/context_pre_go17.go, domains.go, droplet_actions.go, droplets.go, floating_ips.go, floating_ips_actions.go, godo.go, godo_test.go, image_actions.go, images.go, keys.go, links.go, load_balancers.go, regions.go, sizes.go, snapshots.go, snapshots_test.go, storage.go, storage_actions.go, tags.go, util/droplet.go, util/droplet_test.go
This patch updates the godo package to use a portable Go context -- a Context that works with Go versions prior to Go 1.7 as well as Go 1.7 and onwards.
=> Portable Go Context Usage

domains.go, domains_test.go
This PR adds TTL field for domain record operations.
By [API docs](https://developers.digitalocean.com/documentation/v2/#create-a-new-domain-record), it's now possible to specify TTL for all domain records.
/cc @mauricio
=> Add TTL property to Domains

README.md, util/droplet_test.go
The oauth2.NoContext variable was deprecated in
golang/oauth2@c10ba270aa0bf8b8c1c986e103859c67a9103061.
=> Remove references to deprecated oauth2.NoContext

droplet_actions.go, droplet_actions_test.go
This PR fixes bug with Droplet Actions on tagged resources.
Current version of `godo` returns pointer on Action for actions on tagged resources, however, [API returns array of actions](https://developers.digitalocean.com/documentation/v2/#acting-on-tagged-droplets). This results in bug where `godo` returns nil pointer instead of array of actions.
/cc @mauricio @aybabtme @andrewsomething
=> droplet_actions: return array of actions instead of action for tagged resources

load_balancers.go, load_balancers_test.go
Updating a LoadBalancer requires a LoadBalancerRequest, which is not
easily creatable from a LoadBalancer.
Serializing the LoadBalancer to JSON and then deserializing it to a
LoadBalancerRequest mostly works, except that Region is a string on
the Request but not on the LB (since the LB returns the entire
Region object), so json.Unmarshal returns an error.
An explicit AsRequest method makes it easier for consumers of the API
to modify existing LoadBalancer objects, and is designed to avoid
modifying attributes on the original LoadBalancer when the
LoadBalancerRequest is modified.
=> Add AsRequest method on LoadBalancer

godo.go, godo_test.go
Per [RFC 7231#5.5.3](https://tools.ietf.org/html/rfc7231#section-5.5.3), it seems to me that we should be preferring this formatting over what we currently have.
I plan to make use of this functionality over at the [terraform-provider-digitalocean#43](https://github.com/terraform-providers/terraform-provider-digitalocean/pull/43) to report the current Terraform version (and distinguish it from other API clients), and so I thought it'd be useful to improve the formatting slightly.
=> Follow User-Agent header field recommendations

domains.go, domains_test.go
`CAA` domain record requires both there properties to be passed.
Validation rules are delegated to the API.
`Flags` as valuable `0` value, that's why `omitempty` does not present in this property.
=> Handle flags & tag properties for CAA domain record

README.md
This PR replaces current authentication example for a better one, fully-runnable one. Personally, I prefer to have a sort of boilerplate code in the README, which I can easily copy and run without additional changes.
/cc @mauricio
=> docs: replace first example with fully-runnable example

storage.go, storage_test.go
Params for ListVolumes only works if you pass in both region and name. It should handle the case where only one is passed in.
=> storage: list volumes should also handle only name or only region params

godo.go
When the DigitalOcean API sometimes returns a non-JSON error message, godo propagates it as a mysterious error "invalid character '<' looking for beginning of value", which really stems from the failure to parse the API error as JSON. See #142.
This PR attempts to rectify the issue by propagating the original error message instead if it's not parseable as JSON.
=> Handle non-json errors from the API

droplet_actions.go, droplet_actions_test.go
Hi, the upgrade droplet action is no longer supported by the v2 API. (See the [droplet-actions endpoint in the docs](https://developers.digitalocean.com/documentation/v2/#droplet-actions))
Quick example script:
```go
package main
import (
"github.com/digitalocean/godo"
"github.com/digitalocean/godo/context"
"golang.org/x/oauth2"
"fmt"
)
const (
pat = "AccessToken"
doid = 12345
)
type TokenSource struct {
AccessToken string
}
func (t *TokenSource) Token() (*oauth2.Token, error) {
token := &oauth2.Token{
AccessToken: t.AccessToken,
}
return token, nil
}
func main() {
tokenSource := &TokenSource{
AccessToken: pat,
}
oauthClient := oauth2.NewClient(context.Background(), tokenSource)
client := godo.NewClient(oauthClient)
action, _, err  := client.DropletActions.Upgrade(context.TODO(), doid)
if …
```
=> Remove upgrade droplet action (deprecated)

domains.go
Creating an MX record with the priority set to `0` currently does not work as the value is lost when marshalling to JSON. This PR removes `omitempty` in order to retain that value.
```
$ doctl compute domain records create "foo.net" --record-type "MX" --record-name "@" --record-data "relay.foo.net." --record-priority "0" --trace
doctl: 2018/04/26 17:18:33 -> "POST /v2/domains/foo.net/records HTTP/1.1\r\nHost: api.digitalocean.com\r\nUser-Agent: doctl/1.0.0-dev+godo/1.1.0\r\nContent-Length: 60\r\nAccept: application/json\r\nContent-Type: application/json\r\nAccept-Encoding: gzip\r\n\r\n{\"type\":\"MX\",\"name\":\"@\",\"data\":\"relay.foo.net.\",\"ttl\":1800}\n"
doctl: 2018/04/26 17:18:33 <- "HTTP/2.0 422 Unprocessable Entity\r\nContent-Length: 118\r\nCache-Control: no-cache\r\nCf-Ray: …
```
=> Allow creating domain records with a priority of 0.

domains.go
We recently introduced a change to the Domains API. It now mirrors the control panel behavior. Domains can be created without needing an IP address (and the automatic A record that goes along with that).
Using godo to do so results in a `422 Data can't be blank` as the IP address attribute is still sent if blank. This PR adds `omitempty` to IPAddress in the `DomainCreateRequest` type.
See: https://developers.digitalocean.com/documentation/changelog/api-v2/create-domains-without-providing-an-ip-address/
=> Allow creating domains without an IP address.

domains.go
Creating an MX record with the weight set to 0 currently does not work as the value is omitted when marshalling to JSON.
=> Allow creating domain records with a weight of 0

CHANGELOG.md, godo.go, tags.go, tags_test.go
This adds support to some new results as well as the new ability to tag images described in https://developers.digitalocean.com/documentation/changelog/api-v2/adding-tagged-uri/ and https://developers.digitalocean.com/documentation/changelog/api-v2/support-for-custom-images-and-image-tagging/.
Similar to https://github.com/digitalocean/droplet_kit/pull/154.
Could you take a peek @mauricio and/or @jrm780 ?
=> Add support to tagging images

CHANGELOG.md, domains.go, droplets.go, firewalls.go, floating_ips.go, godo.go, load_balancers.go, projects.go, projects_test.go, storage.go, strings.go
this adds support to the **beta** projects API. Please reference https://developers.digitalocean.com/documentation/v2/#projects---beta for the endpoints and request structures.
cc @hugocorbucci @austenito @mauricio
=> add projects support [beta]

images.go, images_test.go
This PR adds support for two recent extensions to the images API: creating custom images and listing images by tag.
https://developers.digitalocean.com/documentation/v2/#create-a-custom-image
https://developers.digitalocean.com/documentation/v2/#list-images-by-tag
=> Add support for creating custom images and listing images by tag.

kubernetes.go, kubernetes_test.go
Removing `defaults` while we revisit the response from the `/v2/kubernetes/options` endpoint.
=> k8saas: remove defaults from options

projects.go
Assigned type switch var to avoid type assertions inside type switch clauses.
Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>
=> remove excessive type assertions

domains.go, domains_test.go
This PR fixes the Domains.EditRecord function so that it correctly return the record's information. This was maskeds by a faulty test fixed here as well. Resolved #198
=> Fix return of Domains.EditRecord function (Fixes: #198).

godo.go
I noticed that the only use of `github.com/tent/http-link-go` was in an unused, non-exported function.  In the interest of eliminating unused code and unnecessary dependencies, here is a pull request to eliminate both the function and the dependency.
=> Remove unused non-exported function so we can eliminate a dependency

CHANGELOG.md, godo.go, tags.go, tags_test.go
this allows the tagging of volumes via godo. Tagging volumes via the tags endpoints was introduced [on Feb 5](https://developers.digitalocean.com/documentation/changelog/api-v2/add-volume-tagging/). See [the tags documentation](https://developers.digitalocean.com/documentation/v2/#tags) for more details.
=> allow tagging volumes

tags.go
Dedicated tagged resources were not added because the API does not expose any LB-related information yet.
Also added some missing GoDocs as a drive-by improvement.
=> Add resource type for load-balancers.

load_balancers.go, load_balancers_test.go
setting this to true will enable proxy protocol support in the loadbalancer
=> add support for enable_proxy_protocol

CHANGELOG.md, databases.go, databases_test.go, godo.go
I noticed that the `database` field was coming in empty while working on the integration into `doctl` and I believe the reason to be because the json field is mislabeled so the database name isn't getting UnMarshaled.
Here is a typical DO API response to show that the field is labeled `db`:
=> fix database pool json field and update patch version

CHANGELOG.md, databases.go, databases_test.go, godo.go
Currently, the json fields for the `CreateDatabasePoolRequest` don't match what the API expects and it's causing it to through 422 responses. This fixes the json fields to match what is expected.
https://developers.digitalocean.com/documentation/v2/#add-a-new-connection-pool
cc: @mikejholly
=> fix create database pool json fields

kubernetes.go, kubernetes_test.go
This PR adds the maintenance policy support for the upcoming Maintenance
Window feature on the Managed Kubernetes service.
=> godo/kubernetes: add maintenance policy support

kubernetes.go, kubernetes_test.go
There are three changes in this PR, all in support of version upgrades for Kubernetes clusters:
1. Support the `upgrading` cluster status, which will be returned from the API when a cluster is in the process of being upgraded.
2. Support the `auto_upgrade` flag when fetching, creating, and updating clusters. When `auto_upgrade` is set to true for a cluster it will be automatically upgraded to new patch versions during its maintenance window.
3. Support fetching available upgrade versions from the `/v2/kubernetes/clusters/{cluster_id}/upgrades` endpoint and requesting an immediate upgrade via the `/v2/kubernetes/clustesr/{cluster_id}/upgrade` endpoint.
=> kubernetes: Add support for upgrades

databases.go, databases_test.go
Adds support for new `private_connection` and `private_network_uuid` fields exposed by VPC-enabled clusters, replicas and pools.
=> Add private connection fields to Databases

databases.go, databases_test.go
Adds support for Redis eviction policy. The endpoint will 404 for non-Redis DB types.
=> dbaas: add support for eviction policy

tags.go
These fields were incorrectly tagged with `omit_empty`, when the correct
tag is `omitempty`.
=> Fix omitempty typos in JSON struct tags

databases.go, databases_test.go
Adds support for remaining operations which allow for custom VPCs.
=> Databases: support for custom VPC UUID on migrate and replica create

databases.go
This adds the `PrivateNetworkingUUID` field to the `DatabaseCreateRequest` to allow users to add a Database to their Virtual Private Cloud.
cc: @mikejholly @hilary
=> dbaas: add private-network-uuid field to create request

README.md
And moved after the headline, it's more common.
=> docs: added GoDoc badge

godo_test.go, kubernetes.go, kubernetes_test.go
The DOKS API relies on presence/non-nil of fields on the incoming request to determine which fields should be patched/updated. If the fields are not present, then they are ignored and not updated.
The `godo.KubernetesNodePoolUpdateRequest` looks like this today:
```go
type KubernetesNodePoolUpdateRequest struct {
Name  string   `json:"name,omitempty"`
Count int      `json:"count,omitempty"`
Tags  []string `json:"tags,omitempty"`
}
```
We define `Count int json:"count,omitempty"`. This means that 1. the field can't be `nil`, and 2. if the field is `0`, because we have `omitempty`, the serialized JSON will exclude this field as "empty" (https://play.golang.org/p/x95nu9gd6FN). So it's not possible to set `Count = 0` for node pools via `godo`.
The `godo.KubernetesClusterUpdateRequest` looks …
=> Support unset fields on Kubernetes cluster and node pool updates

CHANGELOG.md, godo.go
Bumps the library version to 1.21.1, so that I can pull in the Go 1.13 upgrade from `doctl`.
=> Prepare for release 1.21.1

godo.go
Removes `u.ResolveReference` call as I think it's cleaner if we just parse from the client's `BaseURL`.
=> remove ResolveReference call

databases.go, databases_test.go
Throughout godo and the `DatabasesService`, we return the object in addition  to the raw response. This updates `GetFirewallRules` to do this as well.
This is technically a breaking change. But as this API has not been publicized to users yet, I think it's the right thing to do.
=> Return []DatabaseFirewallRule in addition to raw response.

links.go, links_test.go
A proposed solution for issue #263 where the `client.Projects.List` function's returned `resp.Links.Pages.Last` value will have a URI and not an empty value despite being on the last page leading to `resp.Links.IsLastPage()` always returning `false`. The `resp.Links.Pages.Next` value is empty on the last page so we can check that value instead to properly determine the last page.
=> Update isLast to check p.Next

registry.go, registry_test.go
Added changes by @adamwg to include support for the `read_write` parameter to generate read-only or read-write credentials for registries.
=> registry/docker-credentials: add support for the read/write parameter

tags.go
Noticed that `VolumeSnapshotResourceType` was incorrectly set to `"volumesnapshot"` instead of `"volume_snapshot"` when unsuccessfully trying to use the constant in a `TagCreateRequest`, so opened this small PR to correct the value.
=> Fix VolumeSnapshotResourceType value volumesnapshot -> volume_snapshot

databases.go, doc.go
Removes the managed databases info from the top-level godoc string. Having this string there, when no other product specific info is there, is confusing. This PR moves this down to the `DatabaseService` godoc string instead in order to be more consistent with the rest of the library.
=> Remove databases info from top-level godoc string

databases.go
Adds all of the valid Redis eviction policy constants for our managed Redis product. This is similar to what we've done with the valid SQL modes and auth plugins.
=> Add valid Redis eviction policy constants

tags.go, tags_test.go
Updates `tags.go`:
- Adds the `DatabaseResourceType` const.
- Adds the `VolumeSnapshots` and `Databases` fields to `TaggedResources`
=> Update Tags support for Volume Snapshots and Databases

storage.go
The previous link does lead to the right anchor.
=> Fix link to block storage API reference

CHANGELOG.md, godo.go, meta.go, snapshots.go, storage.go, storage_test.go
This change deserializes [the meta field](https://developers.digitalocean.com/documentation/v2/#meta) into the response, allowing easy access to the total number of objects returned by API operations yielding collections.
We also remove links and meta fields from stubbed getters that do not return collections: according to the respective documentations, [links](https://developers.digitalocean.com/documentation/v2/#links) and meta fields won't be included for single element responses.
For now, I have only implemented the change for storage (volumes and snapshots). I'd appreciate getting some initial feedback on the approach, after which I'm more than happy to support all other collection-returning API operations as well.
=> Deserialize meta

CHANGELOG.md, balance.go, balance_test.go, godo.go, godo_test.go
Adds `balance.go` with a `Balance.Get` method.  This currently hard codes the path with `my` as a customer identifier.
=> Return balance values from Balance.Get

CHANGELOG.md, databases.go, databases_test.go
This PR adds a method to allow a user to reset the auth method used by a MySQL DBaaS user. The corresponding public API feature is not released yet.
This is my first PR to godo so let me know if I've missed anything.
There will be a corresponding PR to droplet-kit and doctl as well.
The new endpoint is
/databases/$UUID/users/$NAME/reset_auth and expects a body
```
{
"mysql_settings": {
"auth_plugin": "NEW_AUTH_TYPE",
}
}
```
DropletKit: https://github.com/digitalocean/droplet_kit/pull/231
doctl: https://github.com/digitalocean/doctl/pull/736
=> Add reset database user auth method

go.sum, kubernetes.go, kubernetes_test.go
This PR fixes `expiry_seconds` in `kubernetes.GetCredentials` request. Before this change parameter just was not passed.
=> Fix param expiry_seconds for kubernetes.GetCredentials request

registry.go
Following [Docker's own terminology](https://docs.docker.com/engine/reference/commandline/login/#login-to-a-self-hosted-registry), this exports the DO registry hostname `registry.digitalocean.com` as a const so users of `godo` can reference it.
=> Export the DO registry hostname as a const

CHANGELOG.md
It looks when we reviewed #299, we forgot to ask that contributor to update the changelog. This PR adds that missing changelog entry.
Thanks to @timoreimann for spotting this!
=> Add missing CHANGELOG.md entry

README.md, godo.go
Updates the README to use the new `godo.NewFromToken("my-token")` method.
Specifically looking for @andrewsomething's feedback on this documentation change, since I'm not sure if there's any risk to changing this that I'm not aware of.
This also updates the previously weird 7-space indentation used in the previous code example to use a more common 4-space indentation.
=> Update README to use NewFromToken

registry.go, registry_test.go
* The DOCR API now includes `TagCount` as a returned field with `repository`. This adds support to `godo` for the new field
=> Add TagCount field to registry/Repository

go.mod, go.sum
Updates the vulnerable `golang.org/x/crypto` dependency.
The `golang.org/x/crypto` package is affected by https://nvd.nist.gov/vuln/detail/CVE-2019-11840. This PR bumps the library to an updated version that doesn't contain the vulnerability.
=> Update vulnerable x/crypto dependency

CHANGELOG.md, godo.go
Prepares to release v1.35.1, which includes a fix for CVE-2019-11840.
=> Prepare to release v1.35.1

registry.go, registry_test.go
It's legal for image repositories to have `/` characters in their names. Our API handles this by allowing for URL-encoded repository names - i.e., to fetch tags for a repository called `bar/baz` in registry `foo` you make a request to `/v2/registry/foo/repositories/bar%2Fbaz/tags`.
=> registry: URL encode repository names when building URLs

apps.go
The log type query param was not correctly hooked up resulting in 400s when requesting logs.
=> apps: fix get logs endpoint not passing in log type

CHANGELOG.md, godo.go
I'd like to get a new release out so that I can reference the app platform support in a digitalocean/doctl PR that adds support for it.
I've followed the steps outlined @ https://github.com/digitalocean/godo/blob/main/CONTRIBUTING.md#releasing.
=> Prep v1.39.0 release

CHANGELOG.md, godo.go
Ensure the response body is fully read and closed before we reconnect to reuse the same underlying TCP connection.
https://golang.org/pkg/net/http/#Body
// The http Client and Transport guarantee that Body is always
// non-nil, even on responses without a body or responses with
// a zero-length body. It is the caller's responsibility to
// close Body. The default HTTP client's Transport may not
// reuse HTTP/1.x "keep-alive" TCP connections if the Body is
// not read to completion and closed.
To ensure http.Client connection reuse, I did the following things:
- Read until Response is complete (i.e. ioutil.ReadAll(resp.Body))
- Call Body.Close() ( resp.body.Close makes the connection available for reuse by others using the same http.Client. It doesn’t close the underlying http or tcp …
=> Reuse TCP Connection

apps.go, apps_test.go
This adds support for requesting a live log url that follows the logs.
=> apps: add support for following logs

domains.go
According to [RFC 2782](https://tools.ietf.org/html/rfc2782), 0 is valid value for port in an SRV reccord:
> The port on this target host of this service. The range is 0-65535.
We currently have `omitempty` set for it which cause 0 to be discarded. Attempting to create a record with 0 for the port results in a 422 error with:
```
POST https://api.digitalocean.com/v2/domains/foobar-test-terraform-jg0j77x3ee.com/records: 422 Port is not a number and Port Port must be an integer between 0 and 65535
```
This is required for https://github.com/digitalocean/terraform-provider-digitalocean/issues/475
=> domains: Allow for SRV records with port 0.

apps.go, apps_test.go
This adds support for aggregate deployment logs when a component name is not specified
=> apps: support aggregate deployment logs

apps.gen.go, apps_test.go
⚠️ This is a breaking change
This updates the apps types to the latest version. This also addresses a bug with JSON marshaling where the generated JSON app specs will contain both a `git` and `github` source key for a component even if in the Go struct only one of them is set. The struct field types were changed to pointers (where it makes sense) to address this.
Since this is a breaking change anyway, I also renamed `Db*` fields to `DB*`.
This also includes a drive-by update to the comments, although they are not perfect. We'll get them to good shape in a different PR.
=> update apps types, address marshaling bug

kubernetes.go
This change adds support for persistent node pool taints, a feature in DOKS to associate Kubernetes taints with current and future nodes of a pool.
Refs digitalocean/DOKS#3
=> Kubernetes: add taints field to node pool create and update requests

apps.gen.go, apps.go, apps_test.go
⚠️ This is a breaking change.
Update the apps types to the latest version, replace some of the hand-written ones with autogenerated types that include the latest fields.
Rename constants to align more closely with Go conventions (e.g. `DeploymentPhase_PendingBuild` instead of `DEPLOYMENTPHASE_PENDING_BUILD`)
I haven't merged this PR's counterpart on our end yet—I'd be happy to make any changes.
=> update apps types to latest

godo_test.go
According to the Go testing package documentation FailNow must be called
from the goroutine running the test, not from other goroutines created
during the test.
A simple error without fatal seems to be sufficient for this test.
=> Fix bug in rate limit race test

CHANGELOG.md, load_balancers.go, load_balancers_test.go
This adds a new field for Load Balancers called `SizeSlug`. This feature is not released/generally available yet. 
I tried to follow the same pattern as other products w.r.t naming the field `Size` vs `SizeSlug`, etc. 
When this field is not present/empty, default behavior is maintained on the backend, just like all the other fields for Load Balancers (algorithm, health check, etc)
Internal ticket number: LBAAS-1582
A release will be required for this, as I will be opening doctl, doccm, and the terraform provider.
=> load balancers: add new size slug field

tags_test.go
Fixes #378 
TestTags_Get (tags_test.go) was with a cyclomatic complexity of 16
**Before:**
```
$ gocyclo -top 10 ./ 
16 godo TestTags_Get tags_test.go:289:1
12 godo (*StorageServiceOp).ListVolumes storage.go:92:1
12 util WaitForActive util/droplet.go:19:1
11 godo (*Client).Do godo.go:324:1
10 godo TestAddOptions godo_test.go:503:1
10 godo TestDo_rateLimit godo_test.go:337:1
9 godo stringifyStruct strings.go:67:1
9 godo TestDroplets_CreateMultiple droplets_test.go:260:1
9 godo (*KubernetesClusterStatusState).UnmarshalText kubernetes.go:292:1
8 godo stringifyValue strings.go:31:1
```
**After:**
```
$ gocyclo -top 10 ./
12 util WaitForActive util/droplet.go:19:1
12 godo (*StorageServiceOp).ListVolumes storage.go:92:1
11 godo (*Client).Do godo.go:324:1
10 godo TestDo_rateLimit …
```
=> refactor: Cyclomatic complexity issue

kubernetes.go, kubernetes_test.go
@andrewsomething - we decided to change routes for the docr integration APIs. Sorry about the inconvenience.
=> kubernetes - change docr integration api routes

.github/workflows/ci.yml
Closes #393 
This PR adds `gofmt` to CI GitHub Action. Running `gofmt -s -w ./` locally applied no changes so code should already be `gofmt`-compliant.
=> Add gofmt to CI GitHub Action

vpcs.go, vpcs_test.go
Adds the `VPCSetDefault()` option, that can be passed in to the `Set` method to set the subject VPC to be a default VPC.
1.) The new `VPCSetDefault ` this PR introduces option only supports setting the `default` boolean value to `true` in the request body, since setting it to `false` is meaningless. Each region must have a default VPC, and un-defaulting a default VPC is an illegal op - the API returns a `403` in this case. 
2.) I changed the style of test significantly for this method, the previous implementation didn't quite test the request body, and the test of the unmarshalled request object seemed redundant.  If this looks good, I can change the other VPC tests to follow a similar approach.
=> VPC: adds option to set a VPC as the regional default

registry.go, registry_test.go
As of GA, users are now required to specify a subscription tier when creating a registry, and can query their subscription. Add support for this to godo. Later, we'll add support for switching tiers as well.
=> registry: Support subscription options

apps.gen.go
* We updated the proto to add `UNSPECIFIED` as the default enum for registry type.
=> apps: add unspecified type to image source registry types

images.go, images_test.go
When reviewing https://github.com/digitalocean/terraform-provider-digitalocean/pull/517, I noticed that godo does not currently support updating an image's distribution or description. The API does: https://developers.digitalocean.com/documentation/v2/#update-an-image
=> images: Support updating distribution and description.

godo.go, godo_test.go
Updates the `NewRequest` logic to prevent the `Content-Type` header from being set on GET, HEAD, and OPTIONS requests. Also prevents a body from being set to anything other than nil for those requests.
This also adds a new client initialization option that allows users to define arbitrary key value pairs that are set as HTTP headers on each request. The intent is that people can use these if they need to set extra headers when using godo behind some kind of proxy.
=> Don't set "Content-Type" header on GET requests

godo.go, godo_test.go
This PR adds some basic input cleaning to `NewFromToken`. I don't think we should be mucking around with an `http.Client` provided by a user, so other approaches to creating a client are not effected. We could potentially add further validation, but that would require adding a `panic`. I think the response from the API should be sufficient in most cases.
=> Add some basic input cleaning to NewFromToken

README.md
ubuntu 14 is no longer available, which makes the example request fail.
=> Updated README example

CHANGELOG.md, godo.go
The changes from https://github.com/digitalocean/godo/pull/422 are needed to support App Platform global env vars in doctl (https://github.com/digitalocean/doctl/issues/934)
=> Prep v1.56.0 release.

apps.gen.go
* Updates apps.gen.go with `DOCKER_HUB` registry type
=> apps: update proto to support dockerhub registry type

droplets.go, droplets_test.go
godo has code that suggests that volumes can be attached to Droplets as part of Droplet create by including the volume name. However, is not something actually supported by the API. It has never been documented as part of the API.
Rather than removing it completely, to prevent existing code from failing to compile this PR adds a comment deprecating it. It also reverses the behavior of `DropletCreateVolume.MarshalJSON()` to prefer ID over Name.
=> Deprecate Name field in godo.DropletCreateVolume

.github/workflows/ci.yml
Go 1.16 has been released: https://golang.org/doc/go1.16
=> Add Go 1.16.x to the testing matrix.

vpcs.go, vpcs_test.go
Looks like this method was never implemented:
https://developers.digitalocean.com/documentation/v2/#list-the-member-resources-of-a-vpc
=> vpcs: Support listing members of a VPC.

kubernetes.go, kubernetes_test.go
Now that there is better support for Kubernetes clusters in projects, we should expose an URN method for `KubernetesCluster` to simplify assignment.
Related: https://github.com/digitalocean/terraform-provider-digitalocean/issues/469
=> k8s: Add URN method to KubernetesCluster.

databases.go, databases_test.go
PEM encoded certificates include new lines and json does not handle them well natively. Instead we expect the certificates to now be returned in base64 encoded form. This updates godo to also support that.
=> dbaas: handle ca certificates as base64 encoded

godo.go, godo_test.go
Error responses from the API can optionally include a `request_id` that can be used to debug issues. This is also included in the `x-request-id` response header.
When no ID is included in the body, this will use the one in the header. This will bubble up the request ID in error messaging for clients like doctl even when it is not included in the response body.
=> CheckResponse: Add RequestID from header to ErrorResponse when missing from body.

floating_ips.go
Currently, when assigning a FLIP to a Droplet, we send a payload like : `{"region":"","droplet_id":243862467}` The service tolerates this, but it is incorrect. `region` and `droplet_id` are mutually exclusive.  Sending any other value besides a blank string results in a 422:
{"id":"unprocessable_entity","message":"Cannot specify Droplet and region, they are mutually exclusive."}
We should avoid it all together by setting `omitempty`
=> flip: Set omitempty for Region in FloatingIPCreateRequest.

apps.go, apps_test.go
The API for fetching logs from an application now supports tailing live logs. This is helpful when applications generate a lot of logs, but only the latest logs are needed.
Once these changes are merged, getting them released as `v1.63.0` would be helpful — my next step is to update `doctl` to add the `doctl apps logs --tail` flag. I looked at `CONTRIBUTING.md` for releasing `godo` but I don't have permission to publish releases, so getting some help from a maintainer would be appreciated!
=> apps: Add tail_lines query parameter to GetLogs function

godo.go
Every time I stumble on this, I think "we should do something about this!" Now I finally am doing something...
`Response.Monitor` is not populated, and I'm not even certain that it has ever been.  `util.WaitForActive` does mention a `monitorURI` which leads to confusion. E.g. https://github.com/digitalocean/godo/issues/243  So I've mentioned `Links.Actions[0].HREF` in the comment as it can be used with that function.
https://github.com/digitalocean/godo/blob/b8ecc7df6ba22a61af08cbf9968d7c4bab14622a/util/droplet.go#L19
=> Mark Response.Monitor as deprecated.

1-click.go, README.md, account.go, action.go, balance.go, billing_history.go, certificates.go, databases.go, domains.go, droplet_actions.go, droplets.go, firewalls.go, floating_ips.go, floating_ips_actions.go, image_actions.go, images.go, invoices.go, keys.go, kubernetes.go, load_balancers.go, monitoring.go, projects.go, regions.go, registry.go, sizes.go, snapshots.go, storage.go, storage_actions.go, tags.go, vpcs.go
The redirects to the new API docs do not map the anchor links. So we need to update these.
=> docs: Update links to API documentation.

CHANGELOG.md, godo.go
- #468 - @notxarb - New alerts feature for App Platform
- #467 - @andrewsomething - docs: Update links to API documentation.
- #466 - @andrewsomething - Mark Response.Monitor as deprecated.
=> Prep v1.65.0 release

domains.go
There is no float64 option for json struct tags in Go.
=> domains: remove invalid json struct tag option

load_balancers.go, load_balancers_test.go
Load balancers is changing its sizing model from a size slug to a size unit.
=> Add size unit to LB API.

kubernetes.go, kubernetes_test.go
`supported_features` is a new field available in the `kubernetes/options` response object. This PR adds support for it.
cc: @adamwg @andrewsomething
=> kubernetes: add supported_features field to the kubernetes/options response

kubernetes.go, kubernetes_test.go
This PR adds support for the `HA` field for the Create and Update requests for Kubernetes. This will allow users to create and update their K8s clusters to highly available control planes.
cc: @andrewsomething @adamwg
=> kubernetes: add support for HA control plane

load_balancers.go, load_balancers_test.go
We are adding this new field which allows the user to turn off the current behavior where an A record is created from the apex domain in the cert pointing to the LB IP when added to the Load Balancer.
=> godo/load-balancers: add DisableLetsEncryptDNSRecords field for LBaaS

kubernetes.go, kubernetes_test.go
This PR removes the `HA` field from the Update request for K8s.
This is a follow-up to the removal of `ha` from `doctl`. https://github.com/digitalocean/doctl/pull/1040
cc: @adamwg
=> k8s/godo: remove ha field from update request

certificates_test.go, domains_test.go, kubernetes_test.go, load_balancers_test.go
This PR simplifies tests. It replaces `t.Error/t.Errorf` with functions from `github.com/stretchr/testify/assert`/`github.com/stretchr/testify/require` packages.
`require` is used when we should abort test and do not proceed with next asserts.
=> Refactor tests: replace t.Errorf with assert/require

metrics/metrics.go, metrics/metrics_test.go, metrics/time.go, metrics/time_test.go, metrics/values.go, metrics/values_test.go, monitoring.go, monitoring_test.go
This PR adds support for retrieving Droplet monitoring metrics.
It also adds a new metrics package which is a minimal copy of `github.com/prometheus/common/model`. It provides only the types needed to work with the Prometheus-style results in a DigitalOcean Monitoring metrics response. I've copied it here as Prometheus' common packages are considered internal to Prometheus. From [their README](https://github.com/prometheus/common):
> This repository contains Go libraries that are shared across Prometheus components and libraries. They are considered internal to Prometheus, without any stability guarantees for external usage.
Initially I had begun implementing it myself before deciding to look for a shared package as the format of the data is well-known. Though, as it is not intended for …
=> Add support for retrieving Droplet monitoring metrics.

apps.gen.go
APPS-4420: This changes gives the option to preserve the route prefix in the forwarded request.
Apps PR: https://github.internal.digitalocean.com/digitalocean/cthulhu/pull/68717
=> APPS-4420: Add PreservePathPrefix to AppRouteSpec

README.md, godo.go, godo_test.go, links.go, links_test.go, registry.go, registry_test.go
**Changes**
- Adds godo support for new endpoints. See docs PR https://github.com/digitalocean/openapi/pull/567 
I did go ahead and create a throwaway project to test these new methods and they work as expected. The token pagination also works well 👍🏻 
**Follow up**
- Changelog / version bump
- Add support to doctl
CON-3907
=> registry: Add ListManfiests and ListRepositoriesV2 api endpoint support + Token pagination

droplets.go, droplets_test.go, godo_test.go
During the create request, it will soon be possible to create droplets
that have no public interface attached to them (droplets that only have
a private interface).
It will also be possible to attach a floating IP address to a droplet
during the create proceess.
This PR sets up the DropletCreateRequest fields to allow for that.
Signed-off-by: Chris Cummer <ccummer@digitalocean.com>
=> Add private networking configuration options to the Create request

registry.go, registry_test.go
Added DOCR Registry and Options region support to reflect API changes added with CON-5476/CON-5477 (not yet deployed). 
Pairs with https://github.com/digitalocean/openapi/pull/589
=> registry: Add registry region support

droplets.go, droplets_test.go, godo_test.go
This option is not currently used by anyone at will some point be renamed to `WithReservedIPAddress`. Rather than keep dead code around, this PR removes it.
The new create options will be added when there's functional API endpoints for them to operate against.
Signed-off-by: Chris Cummer <chriscummer@me.com>
=> Remove the WithFloatingIPAddress create option

droplets.go, droplets_test.go, godo_test.go
This option is now set from within the backend based on internal considerations and is no longer user-definable.
Signed-off-by: Chris Cummer <chriscummer@me.com>
=> Remove DisablePublicNetworking option from the Create path

databases.go, databases_test.go
This add `project_id` to the database response and allows the `project_id` to be passed in during the create.
=> Adding project_id to databases

util/droplet_test.go
This updates the wait for active example to:
* Use the simpler way of creating a godo client, and
* Create a real Droplet and show how to find the action URL from the create response.
=> util: update droplet create example

account.go, account_test.go, floating_ips_actions_test.go, godo.go, godo_test.go, projects_test.go, reserved_ips.go, reserved_ips_actions.go, reserved_ips_actions_test.go, reserved_ips_test.go
Floating IPs are being renamed to Reserved IPs. We'll need to
support both for awhile, treating them as distinct resource
types until Floating IPs are deprecated or removed.
This change allows the caller to use either or both at the same
time.
Signed-off-by: Chris Cummer <chriscummer@me.com>
=> Add support for Reserved IP addresses

balance.go, billing_history.go
Updates two links in the godo GoDoc comments that pointed to out-of-date anchor URLs.
=> Update links to API documentation

databases.go, databases_test.go, godo_test.go
This adds support for the advanced DBaaS config endpoints. A few things to note:
- We provide consts for use with `SetEvictionPolicy` method. Unfortunately, those are  in a slightly different format than what can be used for `RedisConfig.RedisMaxmemoryPolicy`. So I attempt to normalize input to `UpdateRedisConfig` if the old consts are used.
- I've used pointer values for the config structs as zero values may be important for some options and it is a PATCH method. It might not be necessary for all of them, but keeping them consistent seemed the best option.
=> databases: Support advanced config endpoints.

apps.go, apps_test.go
Projects have supported apps for sometime now. To simplify adding an app to a project, this exposes an `URN()` method like other resources with projects support.
Related: https://github.com/digitalocean/terraform-provider-digitalocean/issues/853
=> apps: Add URN() method.

floating_ips.go, floating_ips_test.go, reserved_ips.go, reserved_ips_test.go
This exposes the `project_id` attribute in both floating IP and reserved IP request and response bodies. While doing this, I also noticed that we document a `locked` attribute in response bodies that is not exposed in godo. So I've added that as well.
=> reserved IPs: Expose project_id and locked attributes.

.github/workflows/ci.yml, tags.go
Update CI to use go 1.18+1.19. This drops CI testing for Go 1.17 which is ok as `godo`'s policy is to ensure support for the two most recent Go versions.
=> update CI for go 1.18 & 1.19

apps.go, apps_accessors.go, apps_accessors_test.go, apps_test.go
* update interface `AppBuildableComponentSpec` to match functions components
* add interfaces `AppDockerBuildableComponentSpec` and `AppCNBBuildableComponentSpec`
* remove deprecated field/accessor `GetEnvironmentSlug`
=> apps: update component spec interfaces

apps.gen.go, apps_accessors.go, apps_accessors_test.go
Adds `DeployOnPush` to DOCR Image specs and related cause detail structs.
=> apps: add docr image deploy on push

CHANGELOG.md, godo.go
Let's cut a release so we can make sure this gets pulled into the next doctl build.
=> Prep v1.86.0 release.

kubernetes.go, kubernetes_test.go
Reverts https://github.com/digitalocean/godo/pull/484 in preparation for HA enablement
=> CON-5657 (Re-)expose public HA enablement flags in godo

CHANGELOG.md, monitoring.go
Adding new public DBAAS rule endpoints to allow `doctl` to validate when creating/updating rules
=> DBAAS-3011: Add new public endpoints for dbaas alerts

apps.gen.go, apps_accessors.go, apps_accessors_test.go
We're releasing changes to our API that will allow folks to assign it to a specific project rather than their default one. This change enables that in godo so that doctl can do this too.
=> Apps: add project id as a parameter to CreateApp and to the App struct

apps.go, apps_test.go, godo.go
The ListApps endpoint can be called with a `with_projects` query parameter to tell it whether or not to fetch the project ids for each project. This is an expensive call which is why it isn't done by default.
~I'm not sure how to add support for this without breaking changes, I'm hoping @andrewsomething you've got some ideas 🙏 This way seemed like the least work for devs who have already used this in their code, as well as for the doctl implementation of this function.~
This now is an addition to the ListOptions struct, which shouldn't be a breaking change 👍
=> apps: add option to get projects data from Apps List endpoint

load_balancers.go, load_balancers_test.go
Jira: https://jira.internal.digitalocean.com/browse/LBAAS-2430
Setting to default 60s if not specified by the user. FWIW this is the current defaults and will be enforced at the lbapi level as well
=> LBAAS-2430 Add support for HTTP idle timeout seconds

billing_history_test.go, databases_test.go, godo.go, godo_test.go, kubernetes_test.go, registry_test.go, vpcs_test.go
Deprecates and changes all of the uses of the various pointer-to style helpers in favour of using a generic one.
I've seen more and more of the `*type` struct fields pop up in new features, so I figure this might offer a more consistent way to create a pointer to a type, rather having to use an old type specific one or have users create their own.
Most of this is PR is changing the use of old test helpers to use the new func. The implementation of the new func [here](https://github.com/digitalocean/godo/pull/579/files#diff-ec6977d0d43eaf44c51775905e491c046f65b6471ed410ca098857ac94f53ecb).
=> Deprecate old pointer helpers, use generic one

CHANGELOG.md, godo.go
Prepares to release v1.91.1 (v1.91.0 was released without a version bump, so it was deleted).
=> Prepare to release v1.91.1

godo.go
This just sorts the lists of services alphabetically to make it a bit easier to parse visually. We had been doing that at one point, but looks like we got lax about it.
=> godo.go: Sort service lists.

load_balancers.go
=> load-balancers: Minor doc fixup

databases.go, databases_test.go
Adds `updatePool` + updates`DatabaseService`, allows for Postgres pool updates through godo,  makes a PUT request to `/v2/databases/$uuid/pools/$poolname`.
```go
import (
"context"
"github.com/digitalocean/godo"
)
func main() {
pat := "..."
dbUUID := "..."
client := godo.NewFromToken(pat)
_, err := client.Databases.UpdatePool(context.Background(), dbUUID, "backend-pool", &godo.DatabaseUpdatePoolRequest{
User:     "username",
Size:     14,
Database: "defaultdb",
Mode:     "transaction",
})
}
```
=> DBAAS-3906: Include updatePool for DB Clusters

databases.go, databases_test.go
**What**
- Exposes `/v2/databases/{uuid}/upgrade` path to allow for major version upgrades to be made (if valid according to the cluster type, current version, available versions, etc.)
=> Add UpgradeMajorVersion to godo

apps.gen.go, apps_accessors.go, apps_accessors_test.go
This PR adds the pending_deployment field to the App Platform App object.  Previously, neither the Deployment or Deployment ID was returned on CreateApp or UpdateApp.  This made it difficult to attribute a deployment to the specific action and any effort would require a subsequent call.  App.PendingDeployment will always be set to the resulting deployment for CreateApp and UpdateApp. For GetApp and ListApps it will be set to the most recent non-cancelled deployment if one exists.
Additionally, this PR adds DeploymentTiming information.
**Edit: In draft until API changes are approved and deployed.**
=> APPS-6813: update app platform - pending_deployment + timing

CHANGELOG.md, godo.go
- #601 - @jcodybaker - APPS-6813: update app platform - pending_deployment + timing
- #602 - @jcodybaker - Use App Platform active deployment for GetLogs if not specified
=> Prep v1.97.0 Release

godo.go, load_balancers_test.go
In the HTTP spec [here](https://www.rfc-editor.org/rfc/rfc2616#section-10.2.5):
> The 204 response MUST NOT include a message-body, and thus is always terminated by the first empty line after the header fields.
As such, if we receive a 204 response, we shouldn't expect or do anything with the response body.
This fixes an error where `json.Decode` would return `io.EOF` when the response body was empty, and the returned `*Response` object was `nil`, preventing callers from accessing any of its populated fields.
Also, update `TestLoadBalancers_CreateValidateSucceeds` accordingly to match the expected behavior.
=> client: don't process body upon 204 response

registry.go, registry_test.go
This PR adds a method to support using the [Validate a Container Registry Name](https://docs.digitalocean.com/reference/api/api-reference/#operation/registry_validate_name) endpoint.
=> Add support for "Validate a Container Registry Name"

load_balancers.go, load_balancers_test.go
Introduce new load balancer `Type` field to allow specifying the type of load balancer to be created: 
- `REGIONAL`: supports target droplets within the same region/vpc
- `GLOBAL`: supports target droplets across multiple regions/vpcs
Omitting the `Type` field in the `Create` request implies `REGIONAL` by default.
=> load balancers: introduce new type field

go.mod, go.sum, godo.go, godo_test.go
Users can opt to use the httpclient from the retryablehttp package when creating a godo client to enable automatic retries and exponential backoff. 
Users can enable using the retryablehttp httpclient by passing in the `SetRetryMax()` option when creating a client using `New()`. Users can then configure the retryWaitMax, and retryWaitMin values.
This first iteration uses the retryablehttp's `DefaultRetryPolicy` and `DefaultBackOff`. By not explicitly setting them, they are the defaults as shown [here](https://github.com/hashicorp/go-retryablehttp/blob/v0.7.4/client.go#L416-L422).
For the test, I passed in retryMax=2 and retryWaitMax=6.0 seconds and retryWaitMin=6.0s:
```
=== RUN   TestRetryableClient_DefaultRetryPolicy
2023/07/13 11:47:20 [DEBUG] GET http://127.0.0.1:53811/foo
2023/07/13 …
```
=> Add retryablehttp Client Option

godo.go
This exports the HTTP client so that can be modified (i.e. chaining Transports).
=> Export the HTTP client.

godo.go, godo_test.go
Historically, godo has not done any logging on its own. When using the new `WithRetryAndBackoffs` option, this is no longer the case. When used, each request is logged to stderr. This is surprising and not always desirable (e.g. for a cli tool like doctl). 
This PR exposes the `go-retryablehttp.Logger` option in the `RetryConfig`. It defaults to `nil` to prevent logging as this matches the historical behavior. A logger can be configured as knowing when/if a request is being retried is useful.
=> Allow configuring go-retryablehttp.Logger

godo.go, godo_test.go
This aims to solve a number of inconsistencies/issues when using `WithRetryAndBackoffs`. Currentlywhen a retry happens:
- The final error response from the API is overwritten with the "giving up after x attempt(s)" error message. It does not include the final status code.
- The error gets  double nested. So calling `err.Error()` returns the messy looking `Get "http://127.0.0.1:45035/foo": GET http://127.0.0.1:45035/foo giving up after 4 attempt(s)`
- The `*godo.Response` returned by the resource methods is nil if there is an error. That is not consistent with existing godo or net/http. If there is an HTTP response, even an errpr, it should be returned.
This uses a custom `ErrorHandler` in order to provide errors that are consistent with a `*godo.ErrorResponse` and a non-nil …
=> Provide a custom retryablehttp.ErrorHandler for more consistent returns using retries.

databases.go, databases_test.go
Adds Kafka as a DBaaS engine. 
Extends the following methods to accept Kafka specific user settings: 
- GetUser
- ListUsers
- CreateUser
Adds Kafka Responses:
- ResetUserAuth
- ListOptions (see: `GetDatabaseOptions`)
Adds support for Topic management:
- ListTopics
- CreateTopic
- GetTopic
- UpdateTopic
- DeleteTopic
=> Add DBaaS engine Kafka

godo.go
Configures a retryable client with default behavior when a godo client is initialized via NewFromToken(). Also refactored the code a bit to eliminate code duplication. 
If you'd like to test:
```
func main() {
ctx := context.Background()
token := "do_token_here"
client := godo.NewFromToken(token)
for i := 0; i < 290; i++ {
println(i)
_, resp, _ := client.Account.Get(ctx)
println(resp.StatusCode)
}
}
```
will yield:
```
2023/08/23 23:43:59 [DEBUG] GET https://api.digitalocean.com/v2/account
117
2023/08/23 23:43:59 [DEBUG] GET https://api.digitalocean.com/v2/account
2023/08/23 23:43:59 [DEBUG] GET https://api.digitalocean.com/v2/account (status: 429): retrying in 7s (4 left)
```
Same behavior is seen for initializing a client via `godo.NewClient()`
=> Make Retrys by Default for NewFromToken()

go.mod, go.sum
This bumps `github.com/stretchr/testify` to v1.8.4 primarily to update our indirect dependency on `gopkg.in/yaml.v2` which is the source of a number of Dependabot alerts.
=> Bump github.com/stretchr/testify to v1.8.4

CHANGELOG.md, godo.go
We have a few notable changes that haven't been released including Kafka support and defaulting to retries in `NewFromToken()`
=> Prep v1.103.0 release.

apps.gen.go, apps_accessors.go, apps_accessors_test.go
This adds the ability to specifically deploy a precise digest for a given image to avoid having specify unique tags and similar workarounds.
=> APPS-7700 Add ability to specify digest for an image

uptime.go
This PR is to support the work I am doing on https://github.com/digitalocean/doctl/pull/1431 as part of #hacktoberfest.
For the validation of the uptime alert comparison field, I followed the same pattern as 
[monitoring.go#L106-L107 AlertPolicyComp](https://github.com/digitalocean/godo/blob/6c7a058657910fe9997ca44b946a5528ee4d7856/monitoring.go#L106-L114)
Please let me know what you think, Thanks!
=> chore: change uptime alert comparison type

CHANGELOG.md
Cuts a new release with the recent changes so that we can get them pulled into doctl
=> Prep v1.104.0 release.

CHANGELOG.md, CONTRIBUTING.md, go.mod, godo.go
A quick bug fix release addressing two issues with the last release:
- [As noted here](https://github.com/digitalocean/godo/pull/634#discussion_r1355310187), setting `go 1.21` in `go.mod` prevents users from easily using the most recent release with Go 1.20 which we support. 
- I neglected to bump the library version in v1.104.0
=> Drop required Go version to 1.20 and document policy.

projects_test.go, uptime_test.go
This PR replaces `ioutil.ReadAll` with `io.ReadAll` in tests.
[io/ioutil](https://pkg.go.dev/io/ioutil) is deprecated:
> Deprecated: As of Go 1.16, the same functionality is now provided by package [io](https://pkg.go.dev/io) or package [os](https://pkg.go.dev/os), and those implementations should be preferred in new code. See the specific function documentation for details.
=> test: Replace deprecated io/ioutil with io

projects_test.go, uptime_test.go
This PR makes the same changes as #621. Additionally, replace `string(resp)` with `resp` because `fmt.Sprintf("%s", string(resp))` is the same as `fmt.Sprintf("%s", resp)` when `resp` has the `[]byte` type.
=> test: use fmt.Fprintf instead of fmt.Fprintf(fmt.Sprintf(...))

godo.go
This adds retries for HTTP/2 `INTERNAL_ERROR` errors to potentially address errors seen with Terraform. Unfortunately, there is not a way for us to mock these while using `github.com/hashicorp/go-retryablehttp`. Though existing test coverage demonstrates that 500 and 429 retries still work as expected.
=> Retry on HTTP/2 internal errors.

databases.go
**What**
- remove `unclean_leader_election_enable` property for topic configuration
**Why**
This property is no longer supported for kafka topics due to the dangerous nature of enabling it
=> Remove unclean_leader_election_enable for topic configuration

CHANGELOG.md, godo.go
Previous release (v1.105.1) didn't get cut:
https://github.com/digitalocean/godo/releases
So this release combines changes in v1.105.1 and after
=> Prep v1.106.0

apps.gen.go, apps_accessors.go, apps_accessors_test.go
As per title.
~~Please don't merge yet. The production code isn't fully rolled out yet.~~
It's in prod now!
=> apps: Add registry_credentials field, GHCR registry type and the egress spec

databases.go, databases_test.go
**What**
Add ability to update a user's `settings` via a PUT request. This will enable other clients to avoid having to recreate user resources when attempting to update `settings`
=> Enhancement: add database user update

apps.go
This new log type captures "previous" logs so that users that see that their app has seen restarts can fetch those old logs and debug them themselves.
=> APPS-8033 Add the RUN_RESTARTED log type

apps.gen.go, apps_accessors.go, apps_accessors_test.go
[APPS-8302](https://do-internal.atlassian.net/browse/APPS-8302) and [APPS-8303](https://do-internal.atlassian.net/browse/APPS-8303)
[APPS-8302]: https://do-internal.atlassian.net/browse/APPS-8302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APPS-8303]: https://do-internal.atlassian.net/browse/APPS-8303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> APPS-8383: Add deprecation intent and bandwidth allowance to app instance size spec

certificates.go, certificates_test.go, godo.go
[NETPROD-3583](https://do-internal.atlassian.net/browse/NETPROD-3583)
[NETPROD-3583]: https://do-internal.atlassian.net/browse/NETPROD-3583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NETPROD-3583] Added name param in ListOption to get resource by name

databases.go, databases_test.go
This PR adds support for `Project Events`:
`GET` on `/v2/databases/<database_id>/events` via `Databases.ListProjectEvents` - lists all of the cluster events.
For details: https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_list_events_logs
=> Add ListDatabaseEvents to Godo

databases.go
This PR aims at enabling UI Connection parameter for Opensearch.
- `ui_connection` provides the connection details for `OpenSearch dashboard`.
=> Enable ui_connection parameter for Opensearch

apps.gen.go, apps_accessors.go, apps_accessors_test.go, apps_test.go
This PR adds a Termination struct to App Platform container components (service, worker, job).  All container components now have the ability to configure the GracePeriodSeconds which defines the wait from sending the SIGTERM signal to begin shutdown, to the SIGKILL (non-ignorable shutdown).  Additionally, services now have a DrainSeconds field to configure a delay between starting termination/removing from load-balancers, and sending the SIGTERM.
=> APPS-8711: container termination controls

apps.gen.go
Update comments for fields that have been marked deprecated in apps.proto.
=> APPS-8386: Add comments to mark deprecation of unused instance size fields

load_balancers.go, load_balancers_test.go
Introduce config flag to support active-passive failover policy for Global Load Balancers.
=> Add support for GLB active-passive failover config

apps.gen.go, apps_accessors.go, apps_accessors_test.go
This PR adds OpenSearch as a Log Destination for App Platform.
=> APPS-8732 - Add OpenSearch as a Log Destination for App Platform.

load_balancers.go, load_balancers_test.go
This change introduces network type support for load balancers resources, which defines the type of network the resource will be accessible from.
=> Add support for lb internal network type

load_balancers.go, load_balancers_test.go
This will allow customers to enable/disable PROXY protocol on their health checks. If no value is provided then it will default to the LBs PROXY protocol config.
=> Add ProxyProtocol to LoadBalancer HealthCheck

kubernetes.go, kubernetes_test.go
Discussed with @timoreimann and figured that we should rename this property and payload from `ControlPlanePermission` to `ControlPlaneFirewall`.
=> Rename control plane permission to control plane firewall

apps.gen.go, apps_accessors.go, apps_accessors_test.go
This PR adds support to App Platform Log Forwarding for an OpenSearch DBaaS cluster destination.
**DO NOT MERGE UNTIL 2024-06-20**
=> APPS-8790 Add support to App Platform Log Forwarding for an OpenSearch DBaaS cluster destination.

apps.gen.go
This PR adds support for `OPENSEARCH` as a DBaaS option for App Platform.
**DO NOT MERGE UNTIL 7/24/2024**
=> APPS-9133 - Add support for OPENSEARCH as a database engine option

databases.go, databases_test.go
`size` is now included in the API response to `GET /v2/databases/{uuid}/replicas/{name}` and `GET /v2/databases/{uuid}/replicas`.
Related: https://github.com/digitalocean/terraform-provider-digitalocean/issues/1185
=> database: Add Size to DatabaseReplica struct

apps.go, apps_test.go
This new parameter allows the `UpdateApp` call to cause an update of all sources (similar to how a `CreateDeployment` call would work), while also updating the spec in one call.
=> APPS-9201 Add `UpdateAllSourceVersions` parameter to update app calls

databases.go, databases_test.go
Adding databases logsinks CRUD support. Will eventually support in CLI tools like doctl and [terraform](https://github.com/digitalocean/terraform-provider-digitalocean/issues/1199)
=> Databases: Add Logsinks CRUD support

databases.go, databases_test.go
This PR aims at updating GODO to include new OpenSearch Index CRUD chnages.
=> Update GODO to include new Openseach index crud changes

databases.go, databases_test.go
Bringing back Logsink support from #711 and #712 as the code got deleted from a rebase.
=> Databases: Bring back Logsink Support

databases.go
Wrong types for IndexDaysMax and Timeout:
[https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_create_logsink](https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_create_logsink
)
=> DB: Fix Logsink Attribute Types

apps.go
These endpoints have been deprecated:
https://docs.digitalocean.com/release-notes/app-platform/#2024-08-01
=> apps: mark ListTiers and GetTier as deprecated

databases.go, databases_test.go
This change adds support for MongoDB advanced configuration in godo.
=> [databases]: add support for MongoDB advanced configuration

databases.go, databases_test.go
This change adds support for Kafka advanced configuration in godo.
API doc for reference: https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_get_config
=> [databases]: add support for Kafka advanced configuration

kubernetes.go, kubernetes_test.go
This exposes the new create requests fields that allow to set custom CIDRs for the cluster and service subnets.
=> DOKS: add custom CIDR fields

databases.go, databases_test.go
This PR is adding a field to the Opensearch advanced configuration. 
The field was overlooked in a previous PR.
=> [databases]: add a missing field to Opensearch advanced configuration

apps.gen.go, apps_accessors.go, apps_accessors_test.go
This adds a new `maintenance.enabled` field to AppSpec to be able to specify whether maintenance mode should be enabled or disabled.
**PLEASE DON'T MERGE UNTIL OCTOBER 22**
=> Add maintenance field to AppSpec to enable/disable maintenance mode

droplet_autoscale.go, droplet_autoscale_test.go
This is a followup on #743 to adjust the underlying query for hard deletion of droplet autoscale pool (i.e. delete the pool as well as all underlying resources).
=> Adjust delete dangerous

monitoring.go, monitoring_test.go
Extends monitoring library to support querying load balancer monitoring endpoints.
=> Add load balancer monitoring endpoints

apps.gen.go, apps_accessors.go, apps_accessors_test.go
This adds a new `maintenance.archive` field to AppSpec to allow users to archive/restore apps.
=> Add archive field to AppSpec to archive/restore apps

droplets.go, droplets_test.go, sizes.go, sizes_test.go
Corresponds to the API changes described in https://github.com/digitalocean/openapi/pull/918
=> Support Droplet GPU information

godo.go, registry.go, registry_test.go
Addresses [DOCR-1201](https://do-internal.atlassian.net/browse/DOCR-1201): 
Add new service `RegistriesService` interface to support Multiple Registry Open Beta API's, including following methods:
- Get
- List
- Create
- Delete
- DockerCredentials
[DOCR-1201]: https://do-internal.atlassian.net/browse/DOCR-1201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOCR-1201: Add new RegistriesService to support methods for multiple-registry open beta

strings.go, strings_test.go
Reviewing https://github.com/digitalocean/godo/pull/749, I noticed that the `Stringify` utility does not handle maps well. For example, the test output before this change would be something like:
map[1:0xc00007a340 2:0xc00007a360 3:0xc00007a380]
Now it is:
map[1:godo.DropletBackupPolicy{DropletID:1, BackupEnabled:true}, 2:godo.DropletBackupPolicy{DropletID:2, BackupEnabled:false}, 3:godo.DropletBackupPolicy{DropletID:3, BackupEnabled:true}]
=> Support maps in Stringify

databases.go
As part of 
https://do-internal.atlassian.net/browse/DBAAS-5519
https://do-internal.atlassian.net/browse/DBAAS-5587
We need to add missing `postgresql` and `mysql` database configs to godo.
=> Add Missing Database Configs for Postgresql and MYSQL

apps.go, apps_test.go
This PR adds a method to obtain websocket URL to exec into components. The websocket URL can be used for sending/receiving console input and output.
=> APPS-9858 Add method to obtain websocket URL to get console access into components

apps.gen.go, apps.go, apps_test.go
This PR adds a method to restart apps, with an option to restart specific components in an app.
=> APPS-9766 Add method to restart apps

databases.go, databases_test.go
According to the [Create a New Database Cluster](https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_create_cluster) I've noticed the `rules` field was missing.
I've added this field to the `DatabaseCreateRequest` struct. And a new `DatabaseCreateFirewallRule` struct.
```
// DatabaseCreateFirewallRule is a rule describing an inbound source to a database
type DatabaseCreateFirewallRule struct {
UUID  string `json:"uuid"`
Type  string `json:"type"`
Value string `json:"value"`
}
```
I didn't use the already existing `DatabaseFirewallRule` because of the following:
- The `CreatedAt` field is not present in the API Create Request. Only when you get the list of firewall rules for a Database.
- The `ClusterUUID` field in the documentation seems to be a bug. This field …
=> Add Rules field to create Databases with Firewall Rules

godo.go, reserved_ipv6.go, reserved_ipv6_actions.go, reserved_ipv6_actions_test.go, reserved_ipv6_test.go
This PR adds the support for ReserveIPv6 to the godo package
=> Add reserved ipv6 changes as Beta

kubernetes.go, kubernetes_test.go
I believe day should be case insensitive.
Related to https://github.com/digitalocean/terraform-provider-digitalocean/pull/1293
=> [kubernetes]: make kubernetes maintenance_policy day case insensitive

godo.go, partner_interconnect_attachments.go, partner_interconnect_attachments_test.go
Bringing in changes from internal fork for the partner interconnect attachments support
=> support partner interconnect attachment operations

kubernetes.go, kubernetes_test.go
A new field is being added to the the /v2/kubernetes/clusters/{id}/user response. Adding it to the godo type as well.
=> add ID field to KubernetesClusterUser response

apps.gen.go, apps_accessors.go, apps_accessors_test.go
The `offline_page_url` allows users to customize the offline page when an app is in maintenance mode or when an app is archived.
=> Add field to customize the offline page during app maintenance

kubernetes.go, kubernetes_test.go
This PR allows users to specify cluster autoscaler configuration in godo during kubernetes create and update. We accept a JSON string as the value for cluster autoscaler configuration.
=> kubernetes: add cluster autoscaler config

partner_interconnect_attachments.go, partner_interconnect_attachments_test.go
The BGP type in the struct should be a pointer since it is an optional parameter.
=> update bgp to be a pointer

kubernetes.go, kubernetes_test.go
Extends the godo public client with new method `GetNodePoolTemplate` which will be used in assisting CA to scale back up from zero. Created a test project with the following code to verify response is returned as expected
```
package main
import (
"context"
"encoding/json"
"fmt"
"github.com/digitalocean/godo"
"log"
"os"
)
func main() {
t := os.Getenv("DIGITALOCEAN_ACCESS_TOKEN")
if t == "" {
log.Fatal("no DO token set")
}
client := godo.NewFromToken(t)
tmpl, _, err := client.Kubernetes.GetNodePoolTemplate(context.TODO(), "<some-cluster-uuid>", "<some-node-pool-name>")
if err != nil {
log.Fatalf("failed to get template %s", err)
}
j, err := json.MarshalIndent(tmpl, "", "   ")
if err != nil {
log.Fatal(err)
}
fmt.Println(string(j))
}
```
Running the code results in the following response …
=> CON-11810 Implement GetNodePoolTemplate endpoint for DOKS godo client

partner_interconnect_attachments.go, partner_interconnect_attachments_test.go
The json tag for `PeerASN` is incorrect causing it to return an error when trying to create a partner interconnect attachment.
=> fix partner interconnect json tag

.github/workflows/ci.yml
Tests failing with:
> This request has been automatically failed because it uses a deprecated version of `actions/cache: v2`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions.
https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
=> ci: upgrade to actions/cache@v4

partner_interconnect_attachments.go, partner_interconnect_attachments_test.go
When the BGP configuration is provided it is also expecting an auth_key for the BGP session.
Also, json tags are expected with a bit different name without this change creating a partner interconnect attachment with a specific BGP configuration can't be done.
=> add auth_key field

kubernetes.go, kubernetes_test.go
Continuation of PR https://github.com/digitalocean/godo/pull/781 to ensure taints are also returned from the new template endpoint
=> CON-11904 Ensure taints are correctly returned via node template endpoint

partner_interconnect_attachments.go, partner_interconnect_attachments_test.go
Request is expecting BGP config input with fields as `local_router_asn` and `peer_router_asn` but response should be in the form of `local_asn` and `peer_asn`
=> fix partner interconnect attachment json request response

kubernetes.go, kubernetes_test.go
Updates the DOKS API to correctly reflect adjustments in the node pool template response for consistent struct naming
=> Fix: Update godo to use simplified template response and provide consistent struct naming

.github/workflows/ci.yml, go.mod
Now that Go 1.24 is out, this updates godo to Go version v1.23, following our policy:
https://github.com/digitalocean/godo/blob/2e0eaabbd1e18eb13ce8d4c2539edba820dcf18f/CONTRIBUTING.md?plain=1#L71-L77
=> Bump Go version to v1.23

partner_network_connect.go, partner_network_connect_test.go
Although the product name is partner network connect, the returned json object is `attachment` not `partner_network_connect`
=> fix partner network connect json tags

partner_network_connect.go, partner_network_connect_test.go
By mistake, I used `"attachment"` as json tag but the actual response is `"partner_attachment"`, see the API response:
=> hotfix: json field name

partner_network_connect.go
Since the public API already returns PNC data as `partner_attachment` there's no need for the custom unmarshaler anymore
=> VPC-4359: remove custom unmarshaler for PNCs

load_balancers.go, load_balancers_test.go
Support  setting and retrieving TLS cipher policy for load balancers
=> Support Load Balancers tls-cipher-policy

apps.gen.go
Add support in App Platform for VALKEY as a new database option. 
GA on 04/30.
=> APPS-11076: Add support for VALKEY as a database engine option

apps.go
This PR updates how query parameters are being sent. As **GetExec()** is a GET method, it doesn't support passing body.
=> Pass GetExec() request params as query params

apps.gen.go
SuccessThreshold and FailureThreshold are counts, not seconds.
=> Update AppServiceSpecHealthCheck comments

apps.gen.go, apps.go, apps_accessors.go, apps_accessors_test.go, apps_test.go
This PR adds support for getting an app's currently running ephemeral compute instances from `/v2/apps/{app_id}/instances`. An optional parameter `GetAppInstancesOpts` has been added to make it future proof.
=> Implement GetAppInstances

partner_network_connect.go, partner_network_connect_test.go
Adds a new field, `redundancy_zone`, to our Partner Network Connect API.
=> partner-network-connect: Add redundancy zone

apps.gen.go, apps_accessors.go, apps_accessors_test.go
This PR exposes `instance_alias` name for `AppInstances` response from `/apps/{app_id}/instances`. Reference: https://docs.digitalocean.com/reference/api/digitalocean/#tag/Apps/operation/apps_get_instances
=> Apps add instance alias

databases.go, databases_test.go
Updated godo to eventually update terraform-provider-digitalocean to address 
[terraform issue](https://github.com/digitalocean/terraform-provider-digitalocean/issues/1380)
```
Running tool: /opt/homebrew/bin/go test -timeout 30s -run ^TestDatabases_CreateDatabaseUserWithMongoUserSettings$ github.com/digitalocean/godo
ok  	github.com/digitalocean/godo	(cached)
```
=> Databases: Add mongo_user_settings

genai.go, genai_test.go
Implemented methods for Knowledge base endpoints for the GenAI Service
- List Knowledge Bases
- Create a Knowledge Base
- List Data Sources for a Knowledge Base
- Add Data Source to a Knowledge Base
- Delete Data Source from a Knowledge Base
- Retrieve Information About an Existing Knowledge Base
- Update a Knowledge Base
- Delete a Knowledge Base
- Attach Knowledge Base to an Agent
- Detach Knowledge Base from an Agent
=> GenAI Knowledgebase endpoints 

CHANGELOG.md, godo.go
Godo new changes :
- #875 - @dependabot[bot] - Bump golang.org/x/oauth2 from 0.23.0 to 0.27.0
- #885 - @SSharma-10 - Added support for Valkey Configuration
- #876 - @SSharma-10 - Added GenAI Additional Operations
=> godo release-1.162.0

partner_network_connect.go, partner_network_connect_test.go
Issue - [APICLI-2888](https://do-internal.atlassian.net/browse/APICLI-2888)
[APICLI-2888]: https://do-internal.atlassian.net/browse/APICLI-2888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> List remote route | removed id field from remote route

CHANGELOG.md, go.mod, godo.go
=> Releasing godo v1.165.1

vpc_nat_gateways.go, vpc_nat_gateways_test.go
add project ID to nat gateway
example:
```
curl -X POST \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $DIGITALOCEAN_TOKEN" \
-d '{
"name": "test-vpc-nat-gateways",
"project_id": "8ac2138d-4310-4562-a077-8018e13ab1fb",
"type": "PUBLIC",
"region": "tor1",
"size": 1,
"vpcs": [
{
"vpc_uuid": "0eb1752f-807b-4562-a077-8018e13ab1fb"
}
],
"udp_timeout_seconds": 30,
"icmp_timeout_seconds": 30,
"tcp_timeout_seconds": 30
}' \
"https://api.digitalocean.com/v2/vpc_nat_gateways"
```
Example response:
```
{
"vpc_nat_gateway": {
"id": "70e1b58d-cdec-4e95-b3ee-2d4d95feff51",
"project_id": "8ac2138d-4310-4562-a077-8018e13ab1fb",
"name": "test-vpc-nat-gateways",
"type": "PUBLIC",
"state": "ACTIVE",
"region": "tor1",
"size": 1,
"vpcs": [
{
"vpc_uuid": …
```
=> LBAAS-3995: add project ID to nat gateway

droplets.go, droplets_test.go
Implements listing of associated resources for Droplets to support the `destroy_with_associated_resources` endpoint.
Closes #911
- Added `DropletAssociatedResource` and `DropletAssociatedResources` structs
- Implemented `ListAssociatedResourcesForDeletion()` method for Droplets service
- Added unit test coverage
- Follows the existing Kubernetes implementation pattern
GET /v2/droplets/{id}/destroy_with_associated_resources
Returns associated billable resources (reserved IPs, floating IPs, snapshots, volumes, volume snapshots) with cost information.
- ✅ Manual testing against live API
- ✅ Unit tests pass
- ✅ All existing droplet tests pass
The Kubernetes service has `DeleteSelective()` and `DeleteDangerous()` methods for actually destroying resources. Should similar deletion methods be …
=> Add ListAssociatedResourcesForDeletion for Droplets
