digitalocean/godo

- droplets.go
Add created_at property in Droplet object
https://developers.digitalocean.com/#droplets
> Add creation date field

- README.md
I updated the pagination example so it compiles and runs as expected.
> Fix the pagination example

- README.md
- action.go
- domains.go
- droplet_actions.go
- droplets.go
- image_actions.go
- images.go
- keys.go
- regions.go
- sizes.go
> Update doc links for v2 documentation.

- droplet_actions.go
- droplet_actions_test.go
>  Add boolean disk option to Resize droplet action.

- CONTRIBUTING.md
- README.md
> Add docs for contributing, versioning and docs.

- action.go
- action_test.go
This adds support for embedded regions as per the change https://developers.digitalocean.com/documentation/changelog/api-v2/actions-breaking-changes-upgrade-path/.
This should wait until 3/20 when the change happens
cc @phillbaker @bryanl
> Add support for embedded region in actions

- README.md
- droplets.go
- droplets_test.go
- godo_test.go
> Add image/ssh key structs for explicit type on droplet create.

- domains_test.go
- droplet_actions_test.go
- droplets_test.go
- godo.go
- godo_test.go
- image_actions_test.go
- keys_test.go
- strings.go
Adds missing error checks to godo. Ensures calls to Client.Do and json decoding are evaluated when neccessary.
> Add missing error checks

- action.go
- action_test.go
- domains.go
- domains_test.go
- droplet_actions.go
- droplet_actions_test.go
- droplets.go
- droplets_test.go
- godo_test.go
- image_actions.go
- image_actions_test.go
- images.go
- images_test.go
- keys.go
- keys_test.go
- regions.go
- regions_test.go
- sizes.go
- sizes_test.go
Make adherenence to interface a compile time rather than a test time check.
> Remove testing Implements

- keys.go
- keys_test.go
* Keys.UpdateByID() for PUT /v2/account/keys/12345
* Keys.UpdateByFingerprint() for PUT /v2/account/keys/<fingerprint>
> Add support for key updates

- droplet_actions.go
- droplet_actions_test.go
This includes the following DropletActions service methods:
DisableBackups, PasswordReset, RebuildByImageID(), RebuildByImageSlug(), ChangeKernel(), EnableIPv6(), EnablePrivateNetworking() and Upgrade().
> Add missing droplet actions.

- droplets.go
- droplets_test.go
Includes ListKernels, ListSnapshots, ListBackups, ListActions and ListNeighbors corresponding to
the GET "/v2/droplets/:id/kernels" etc. APIs.
> Add Droplet service Listing requests.

- droplets_test.go
- sizes.go
- sizes_test.go
* Added transfer to size
* Added available to size
> Added parameters to size 

- domains.go
Remove fmt.Printf from domains.go
> Remove fmt.Printf from domains.go

- droplets.go
> remove unexported items from interfaces

- util/droplet_test.go
Move the `oauth2` dependency to the new library.
Signed-off-by: Tim <timfall@gmail.com>
> Update oauth2 dependency

- README.md
- account.go
- domains.go
- droplet_actions.go
- droplets.go
- godo.go
- image_actions.go
- images.go
- keys.go
- regions.go
- sizes.go
- strings.go
> It's DigitalOcean

- floating_ips.go
- floating_ips_actions.go
- floating_ips_actions_test.go
- floating_ips_test.go
- godo.go
This adds support for floating IPs, an upcoming feature.
@bryanl @phillbaker @brookemckim
> add support for floating IPs

- account.go
- account_test.go
Fields: `Status` and `StatusMesssage`
> Adds missing account fields

- droplet_actions.go
- droplet_actions_test.go
> Added EnableBackups plus test

- floating_ips_actions.go
- floating_ips_actions_test.go
We'll also need to accept ListOptions for FloatingIPActions.List like other List functions in order to deal with pagination.
@bryanl, @carlosdp
> Accept ListOptions for FloatingIPActions.List

- account.go
- account_test.go
Update Account to include `FloatingIPLimit` which is now provided by the `/v2/account` controller.
> Add FloatingIPLimit to Account

- droplets.go
- droplets_test.go
Adds Multiple Droplet Create support by way of `CreateMultiple`.
> Multiple droplet create support

- godo.go
Headers were changed to
* `RateLimit-Limit`
* `RateLimit-Remaining`
* `RateLimit-Reset`
> updating rate limit headers

- droplet_actions.go
- droplet_actions_test.go
- droplets.go
- droplets_test.go
- godo.go
- tags.go
- tags_test.go
This adds in support for the tagging api documented @ https://developers.digitalocean.com/documentation/v2/tagging-preview.
cc @phillbaker
> Add support for tagging api

- droplets.go
- droplets_test.go
With DigitalOcean's tags API, Droplets now include tags.
> Add tags to droplets

- storage_actions.go
- storage_actions_test.go
Also add List and Get functions for StorageActions for consistency with other resources.
> Add support for resizing volumes.

- storage_actions.go
- storage_actions_test.go
> Adds DetachByDropletID

- action.go
- droplet_actions.go
- floating_ips_actions.go
- image_actions.go
- images.go
- keys.go
- regions.go
- storage_actions.go
Similar to:
* https://github.com/digitalocean/godo/blob/master/droplets.go#L120
* https://github.com/digitalocean/godo/blob/master/floating_ips.go#L42
* https://github.com/digitalocean/godo/blob/master/storage.go#L69
* https://github.com/digitalocean/godo/blob/master/account.go#L30
* https://github.com/digitalocean/godo/blob/master/domains.go#L40
> Object roots should use a pointer to be consistent.

- README.md
@aybabtme  Updates to the README to reflect #113
> Update README with context.Context usage.

- droplets.go
This change set addresses issue https://github.com/digitalocean/godo/issues/109.
> Fix typos in PublicIPv6()

- storage.go
- storage_test.go
The API supports creating Volumes based on snapshots, godo should too.
> Support creating Volumes from snapshots.

- README.md
> Fix Example in README.md

- storage.go
- storage_test.go
Add support for creating formatted volumes, and reading the format of existing volumes.
> storage: Add support for volume formatting

- CHANGELOG.md
- cdn.go
- cdn_test.go
- godo.go
> Storage: fix cdn flush cache endpoint and fix changelog

- account.go
- account_test.go
our public api now exposes `volume_limit` 🎉 
this is required on kubernetes csi https://github.com/digitalocean/csi-digitalocean/issues/31
> Adding `VolumeLimit` to account

- CHANGELOG.md
- godo.go
- #178 Allowing creating domain records with weight of 0 - @TFaga
- #177 Adding `VolumeLimit` to account - @lxfontes
> Releasing 1.4.2

- godo.go
- kubernetes.go
- kubernetes_test.go
Adds support for the Kubernetes endpoints in the client.
r: @nanzhong @bouk @fatih @joonas @marc-barry
> k8saas: add support for Kubernetes endpoints

- CHANGELOG.md
This includes a tag so that consumers can target this release of the package.
> release 1.7.2

- CHANGELOG.md
- cdn.go
- cdn_test.go
- godo.go
> CDN: Add support for configuring custom subdomains in Spaces CDN.

- storage.go
- storage_test.go
- Add tags field for storage volumes.
- Add tags field to tests.
> Add tags for storage volumes

- databases.go
- databases_test.go
- doc.go
- godo.go
Adds library support for the new Databases API endpoints.
> Adds support for Databases

- CHANGELOG.md
- godo.go
- #213 Add tagging support for volume snapshots - @jcodybaker
> godo: new v1.13.0 release

- projects.go
- Previous link that's in the code results in a 404
> Fix doc link

- kubernetes.go
- kubernetes_test.go
Deprecate RecycleNodePoolNodes
CON-1696
> kubernetes: Add DeleteNode method

- CHANGELOG.md
- godo.go
* Add entry to CHANGELOG
* Bump libraryVersion
> Prepare v1.16.0

- CHANGELOG.md
- godo.go
- #238 Add support for Redis eviction policy in Databases @mikejholly
> Release 1.17.0

- databases.go
> Add the ability to get URN for a Database

- CHANGELOG.md
- godo.go
- #241 Databases: support for custom VPC UUID on migrate @mikejholly
- #240 Add the ability to get URN for a Database @stack72
- #236 Fix omitempty typos in JSON struct tags @amccarthy1
> Release 1.18.0

- CHANGELOG.md
- godo.go
#244  dbaas: add private-network-uuid field to create request
> release 1.19.0

- CHANGELOG.md
- kubernetes.go
- kubernetes_test.go
Add Kubernetes GetUser that retrieves cluster-specific details for the authenticated user.
> Add Kubernetes GetUser

- CHANGELOG.md
- kubernetes.go
- kubernetes_test.go
This PR adds fields for Kubernetes NodePool autoscale support.
> Add Kubernetes node pool autoscale fields

- databases.go
- databases_test.go
Fixes #249 
Added tags field to required structures + updated corresponding tests
> Add tags to Database, DatabaseReplica

- CHANGELOG.md
- kubernetes.go
- kubernetes_test.go
Adds a new endpoint for getting cluster credentials.
> Add Kubernetes GetCredentials method

- CHANGELOG.md
- godo.go
Rebased on top of https://github.com/digitalocean/godo/pull/259 until it's merged. DO NOT MERGE until then 🙏
> Release v1.22.0

- databases.go
- databases_test.go
adds support for adding firewall rules (inbound sources) for the
database clusters via the public api
> add support for getting/setting firewall rules

- CHANGELOG.md
- godo.go
This should've been v1.23.0, but I did the release steps in the wrong order 🤦‍♂
> Prepare for release v1.23.1

- CHANGELOG.md
- godo.go
> Prepare for release v1.24.0

- CHANGELOG.md
- godo.go
> Prepare for release v1.24.1

- registry.go
- registry_test.go
> implement the registry/docker-credentials endpoint

- CHANGELOG.md
- godo.go
Prepares `godo` for release v1.25.0.
> Prepare for release v1.25.0

- databases.go
- databases_test.go
Adds support for SQL Mode get and set.
> dbaas: get and set mysql sql mode

- CHANGELOG.md
- godo.go
> Prepare for release v1.27.0

- registry.go
- registry_test.go
Registries now have creation times.
> registry: Support the created_at field

- CHANGELOG.md
- databases.go
- databases_test.go
Reverts digitalocean/godo#298
We don't want this in the upcoming release so I'm reverting for the time being.
> Revert "Add reset database user auth method"

- CHANGELOG.md
- databases.go
- databases_test.go
This is a rehash of https://github.com/digitalocean/godo/pull/298
At the time we hadn't released the feature on the backend so we chose to hold off on the Godo release. We are now ready to release it.
> Add Reset MySQL Auth

- CHANGELOG.md
- godo.go
> Create a release candidate for mysql auth

- CHANGELOG.md
Add #310 to the changelog, fix pull number on the last entry.
> Add BillingHistory to changelog, sync with releases

- CHANGELOG.md
- load_balancers.go
- load_balancers_test.go
Internal ticket number for reference: LBAAS-1374
> load balancers: add new enable_backend_keepalive field

- CHANGELOG.md
- godo.go
Prepares the repo for a v1.35.0 release.
> Prepare v1.35.0 release

- registry.go
- registry_test.go
The `/v2/registry/docker-credentials` endpoint supports an `expiry_seconds` query param, but this has not been exposed in godo yet.
https://developers.digitalocean.com/documentation/v2/#get-docker-credentials-for-container-registry
> By default, the returned credentials will not expire. To retrieve credentials with an expiry set, expiry_seconds may be provided as a query parameter. For example: /v2/registry/docker-credentials?expiry_seconds=3600 will return credentials that expire after one hour.
This unblocks work on the DigitalOcean Terraform provider.
> Expose expiry_seconds for Registry.DockerCredentials.

- 1-click.go
- 1-click_test.go
- godo.go
This adds the functionality to the godo client to call the 1-click api.
> add 1-click service and request

- README.md
After my PR was merged I realised that it did not compile
:facepalm:
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
> Make readme exemple compile

- godo.go
- godo_test.go
Fixes #291 
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
> Make Rate limits thread safe

- CHANGELOG.md
- godo.go
> Prep v1.41.0 release.

- invoices.go
- invoices_test.go
This PR adds `Category` to `InvoiceItem`.
> invoices: add category to InvoiceItem

- apps.gen.go
- apps.go
- apps_test.go
This updates the App Platform type definitions to reflect the latest state
> update apps types

- CHANGELOG.md
- godo.go
Cut a release to unblock https://github.com/digitalocean/doctl/pull/854
> Prep v1.45.0 release.

- CHANGELOG.md
- godo.go
Bumps the version for v1.46.0.
> Prepare to release v1.46.0

- apps.gen.go
- databases_test.go
- firewalls_test.go
- kubernetes_test.go
- load_balancers_test.go
Fixes #375
I have run the command `gofmt -s -w ./` as suggest in the issue #375
> Run gofmt to fix some issues in codebase

- databases.go
- domains.go
- droplets.go
- firewalls.go
- floating_ips.go
- images.go
- images_test.go
- invoices.go
- kubernetes.go
- load_balancers.go
- load_balancers_test.go
- projects.go
- storage.go
- strings.go
Signed-off-by: Siddharth Subramanian <sidsbrmnn@gmail.com>
> Fix golint issues #377

- kubernetes.go
- kubernetes_test.go
Pull request for https://github.com/digitalocean/godo/issues/334
> Add GetKubeConfigWithExpiry (#334)

- apps.gen.go
- databases.go
> Fixed some typo in apps.gen.go and databases.go file or issue #376

- kubernetes.go
- kubernetes_test.go
> kubernetes - add registry related doks apis

- CHANGELOG.md
- godo.go
> Prepare to releave v1.47.0

- apps.gen.go
Latest updates to `apps.gen.go`
> apps: pull in recent updates to jobs and domains

- apps.gen.go
This PR adds `InternalPorts` to the `AppServiceSpec`.
> apps: add service spec internal ports

- apps.gen.go
- apps.go
- apps_test.go
Let me know if the naming of the new types is ok or if we should add `App` prefixes to any of them.
> apps: add ListRegions, Get/ListTiers, Get/ListInstanceSizes

- .github/workflows/ci.yml
Fixes #391 
Use the official Golang action instead of golang-pipeline.
> Update to official golang action

- .github/workflows/ci.yml
> Add support for caching dependencies between GitHub Action runs

- CHANGELOG.md
- godo.go
> Prepare to release v1.51.0

- apps.go
- apps_test.go
cURL usage:
```
curl \
-H "Content-Type: application/json" \
-H "Authorization: Bearer TOKEN" \
"https://api.digitalocean.com/v2/apps/ID/deployments" \
-XPOST \
-d '{"force_build": true}'
```
> apps: add the option to force build a new deployment

- apps.gen.go
* Adds support for image source spec
> apps: update spec to include image source

- kubernetes.go
- kubernetes_test.go
Add support to run clusterlint and fetch diagnostics. 
cc @adamwg
> kubernetes: add clusterlint support

- CHANGELOG.md
- godo.go
> update changelog and library version

- apps.gen.go
- apps.go
- apps_test.go
This implements the ProposeApp endpoint. Addresses #415 & #419
> apps: add ProposeApp method

- apps.gen.go
This change updates the apps.gen.go with the GitLab protos.
> apps: updates apps.gen.go for gitlab addition

- kubernetes.go
- kubernetes_test.go
Support list associated resources for deletion and the new cluster delete endpoints.
cc @MorrisLaw , @adamwg
> kubernetes - support optional cascading deletes

- CHANGELOG.md
- godo.go
@andrewsomething , @ChiefMateStarbuck  - I need a new godo release to update doctl and terraform provider. Can you please make a new release after merging this?
> Prepare v1.57.0 release

- kubernetes.go
- kubernetes_test.go
This PR adds the name field to the Kubernetes associated resources struct.
> kubernetes: add name field to associated resources

- CHANGELOG.md
- godo.go
> Prep v1.58.0 release.

- databases.go
- databases_test.go
https://developers.digitalocean.com/documentation/v2/#restore-from-a-database-cluster-backup
> dbaas: Support restoring from a backup.

- apps.go
- apps_test.go
Pre-req for fixing this issue in `doctl` - https://github.com/digitalocean/doctl/issues/975
> apps: Support pagination.

- apps.gen.go
- apps_test.go
Update the `AppCORSPolicy` type with the new cors fields
> app spec: update cors policy

- databases.go
- databases_test.go
This adds support for retrieving the cluster CA cert for dbaas clusters.
> dbaas: add support for getting cluster CA

- droplets.go
- droplets_test.go
- godo_test.go
> add with_droplet_agent option to create requests

- CHANGELOG.md
- godo.go
> Prep v1.63.0 release

- apps.gen.go
- apps.go
- apps_test.go
New Functions:
ListAlerts - This is a way to list the alerts associated to an app and its components.
UpdateAlertDestinations - This is a way to update the emails and slack web hooks that receive messages when alerts get triggered.
This includes an updated apps.gen.go file to be able to support new App Platform features.
> New alerts feature for App Platform

- CHANGELOG.md
- godo.go
> Prepare to release v1.69.0

- CHANGELOG.md
- godo.go
> Prepare to release v1.69.1

- action.go
- apps.go
- databases.go
- domains.go
- droplet_actions.go
- droplets.go
- godo.go
- image_actions.go
- keys.go
- kubernetes.go
- registry.go
- snapshots.go
- storage_actions.go
- util/droplet_test.go
This PR fixes typos and grammar issues. Does not affect production code.
> Fix typos and grammar issues in comments

- CHANGELOG.md
- godo.go
> Prepare to release v1.70.0

- apps.gen.go
Updates apps spec to add Log Destination types to support log forwarding feature.
> apps: update spec to include log destinations

- CHANGELOG.md
- godo.go
Cutting a new release so we can pull this into doctl. https://github.com/digitalocean/doctl/issues/1059
> Prep v1.71.0 release.

- CHANGELOG.md
- godo.go
Cutting a new release to update doctl.
> Prep v1.72.0 release

- CHANGELOG.md
- godo.go
Release for https://github.com/digitalocean/godo/pull/501
> Prep v1.73 release

- apps.gen.go
- apps_test.go
This PR makes `godo` changes to introduce the upcoming `functions` app component.
> Add new component type to apps-related structs

- CHANGELOG.md
- godo.go
> Prepare to release v1.74.0

- CHANGELOG.md
- godo.go
> Prepare to release v1.75.0

- load_balancers.go
- load_balancers_test.go
> load-balancers: add support for validating create and update requests

- CHANGELOG.md
- godo.go
> Prep v1.76 release

- apps.gen.go
* Add FunctionsActivationCount/FunctionAverageDurationMS alerts
* Add AppIngressSpec
* Add missing TLSInsecure to AppLogDestinationSpec
* Add LoadBalancerID to Deployment
> apps: Update apps protos

- CHANGELOG.md
- godo.go
- #522 - @jcodybaker - app platform: add support for features field
> prepare v1.78.0 release

- apps.gen.go
* Add AppAlertSpecRule_FunctionsGbRatePerSecond functions alert rule type
* Update AppDomainSpec.MinimumTLSVersion to no longer accept 1.0 and 1.1
* Spelling Corrections.
> APPS-5636 - App Platform updates

- CHANGELOG.md
- godo.go
Dated for Monday as it is already past 6PM on the east coast.
CC: @ElanHasson
> Prep v1.80.0 release.

- droplets.go
- droplets_test.go
See: https://github.com/digitalocean/openapi/pull/686
> droplets: Support listing Droplets filtered by name.

- CHANGELOG.md
- floating_ips.go
- godo.go
- reserved_ips.go
:facepalm:  These should have `omitempty`. Doing a quick bugfix release.
> reserved IPs: project_id should have omitempty in create req.

- CHANGELOG.md
- godo.go
CC: @timoreimann, @dylanrhysscott
> Prep v1.87.0 release.

- CHANGELOG.md
- godo.go
> Prep v1.89.0 release

- image_actions.go
- util/image.go
- util/image_test.go
I'd like to use this to add a `--wait` option to `doctl compute image create`.
> Add WaitForAvailable

- CHANGELOG.md
- godo.go
> Prep v1.92.0 release

- CHANGELOG.md
Needed to unblock https://github.com/digitalocean/doctl/pull/1327
> Prep v1.93.0 release.

- CHANGELOG.md
- godo.go
needed to update terraform-do-provider
> Prep godo v1.94.0 Release

- CHANGELOG.md
- databases.go
- databases_test.go
Also Adding unit test for the new method.
> Adding PromoteReplicaToPrimary to client interface.

- CHANGELOG.md
- godo.go
- #599 - @markpaulson - Adding PromoteReplicaToPrimary to client interface.
> Prep v1.96.0

- apps.go
- apps_test.go
> Use App Platform active deployment for GetLogs if not specified

- apps.gen.go
- apps_accessors.go
- apps_accessors_test.go
also add:
- ListBuildpacksResponse
- Godoc Updates
- EnvSlug Accessors
> add apps rewrites/redirects to app spec

- CHANGELOG.md
- godo.go
Changelog:
- #608 - @anitgandhi - client: don't process body upon 204 response
- #607 - @gregmankes - add apps rewrites/redirects to app spec
> prep v1.98.0 release

- CHANGELOG.md
- godo.go
> Prepare to release v1.99.0

- CHANGELOG.md
- godo.go
Prepares to release godo v2.0.0.
> Prepare to release v1.100.0

- links_test.go
This PR fixes `TestLinks_ParseURL`.
> test: add missing error check

- CHANGELOG.md
- godo.go
> Prep v1.107.0 release.

- load_balancers.go
Introduce new Load Balancer type `REGIONAL_NETWORK`
> load balancer : add regional network as new LB type

- apps.gen.go
- apps_accessors.go
- apps_accessors_test.go
Add new field single_instance_only to app instance sizes. Also updated accessor to the latest in apps.
> APPS-8315: Update app instance size spec

- databases.go
- databases_test.go
This PR aims at enabling opensearch engine option and listing of database events in Godo.
> Enable Opensearch option in Godo

- apps.gen.go
- apps_accessors.go
- apps_accessors_test.go
> Revert "APPS-8732 - Add OpenSearch as a Log Destination for App Platform."

- apps.gen.go
Update documentation on App Platform OpenSearch endpoint structure.
> APPS-8732 - Update documentation on App Platform OpenSearch endpoint structure.

- CHANGELOG.md
- godo.go
```
$ github-changelog-generator -org digitalocean -repo godo -token $GH_TOKEN
- #708 - @markusthoemmes - APPS-9201 Add `UpdateAllSourceVersions` parameter to update app calls
- #706 - @andrewsomething - database: Add Size to DatabaseReplica struct
```
CC: @markusthoemmes
> Prep v1.120.0 release

- databases.go
- databases_test.go
This PR aims at adding support for Opensearch acl.
> Databases: Add support for OpenSearch ACL

- CHANGELOG.md
> [release]: prep v1.127.0

- godo.go
Sorry, forgot to update a library version to release 1.127.0
> [release]: prep 1.127.0 update library version

- apps.gen.go
- apps.go
- apps_accessors.go
- apps_accessors_test.go
- apps_test.go
Adds bitbucket as a new git source to create apps.
> APPS-9365: Add bitbucket source to App Spec

- load_balancers.go
- load_balancers_test.go
add network_stack field to load balancers model
> LBASA-3620: add network_stack field to load balancers model

- CHANGELOG.md
- godo.go
> release: prepare v1.136.0

- kubernetes.go
- kubernetes_test.go
k8saas PRs need to be rolled out first.
> add flags for doks routing-agent plugin

- spaces_keys.go
- spaces_keys_test.go
> support Spaces Keys GET by Access Key ID

- CHANGELOG.md
- godo.go
> release: prepare v1.140.0

- kubernetes.go
- kubernetes_test.go
> add support for cluster status messages

- CHANGELOG.md
- godo.go
> prepare to release v1.141.0

- godo.go
- partner_network_connect.go
- partner_network_connect_test.go
- change naming to match product rename
> fix partner attachment rename

- CHANGELOG.md
- godo.go
> Prepares to release v1.143.0

- databases.go
- databases_test.go
**What**
- Adds support for Valkey in database options
> Support Valkey in DatabaseOptions

- apps.gen.go
- apps_accessors.go
- apps_accessors_test.go
Adds app spec changes for subdomain routing to godo.
> Bring app spec changes for subdomain routing to godo

- CHANGELOG.md
- godo.go
This PR depends on : https://github.com/digitalocean/godo/pull/831 to be merged & rebased.
> APPS | Add release notes for GetAppInstances implementation v1.147.0

- kubernetes.go
- kubernetes_test.go
New feature in DOKS. doctl changes and public docs updates to come after some more testing.
> expose custom Kubernetes CA expanders

- apps.gen.go
- apps_accessors.go
- apps_accessors_test.go
This RP includes changes related to App Platform's edge control settings.
> Add App Platform Edge Control settings

- CHANGELOG.md
- godo.go
Release the changes from https://github.com/digitalocean/godo/pull/847
> Add instance alias release notes

- apps.gen.go
- apps.go
- apps_test.go
Adds `GetAppHealth()` call to apps
> APPS: expose app health

- genai.go
- genai_test.go
Implemented methods for OpenAI API Key endpoints for the GenAI Service :
- List OpenAI API Keys
- Create OpenAI API Key
- Get OpenAI API Key
- Update OpenAI API Key
- Delete OpenAI API Key
- List agents by OpenAI Key
> Added OpenAI API Key Operations 

- CHANGELOG.md
- godo.go
> prep v1.158.0

- apps.gen.go
- apps_accessors.go
- apps_accessors_test.go
This PR adds a vpc fields to AppSpec to allow VPC integration for App Platform.
> Add VPC Integration

- CHANGELOG.md
- godo.go
Godo changes :
- #871 - @ShivaniKumar1 - Add VPC Integration
> Prep v1.159.0

- apps.gen.go
- apps_accessors.go
- apps_accessors_test.go
This pull request introduces a new alert rule for autoscaling success.
> APPS - Add Autoscale succeeded alert support

- genai.go
- genai_test.go
Added Godo changes for ListIndexingJobs.
Added unit tests for all the changes.
Manually verified that the changes work through a Go script.
Revert commit
> GenAI - added changes for ListIndexingJobs for a Knowledge Base

- CHANGELOG.md
- godo.go
> Release 1.164.0
